#!/usr/bin/env bash
# ssa_stress: yosys-oracle + Z3 miter against our Verible→BIR pipeline.
#
# For each rand_*.sv generated by random_sv_gen --features ssa_stress:
#   1. yosys reads the SV (SV-2005 subset — `wire`/`reg`, plain
#      `always @`), elaborates+flattens+opt's, dumps RTLIL → parsed
#      into BIR via Sv_rtlil_reader / Rtlil_to_behavioral.
#   2. verible reads the same SV → Verible_to_behavioral BIR.
#   3. Z3_miter.check_miter_equivalence formally compares the two BIRs.
#
# Both paths produce a BIR; the miter is Z3.  test_yosys_vs_verible
# does all of this in one binary.
#
# Args: [--seed N] [--n K]  (defaults seed=1, n=50).
set -u
cd "$(dirname "${BASH_SOURCE[0]}")/../.."
eval "$(opam env --switch=5.3.0)"
GEN=./_build/default/random_sv_gen.exe
MITER=./_build/default/test_ssa_stress_miter.exe
[ -x "$GEN"   ] || dune build ./random_sv_gen.exe         >/dev/null
[ -x "$MITER" ] || dune build ./test_ssa_stress_miter.exe >/dev/null

SEED=1
N=50
while [ $# -gt 0 ]; do
  case "$1" in
    --seed) SEED=$2; shift 2;;
    --n)    N=$2;    shift 2;;
    *) echo "unknown arg: $1"; exit 2;;
  esac
done

OUT=/tmp/ssa_stress
WORK=$OUT/work
FOUND=$OUT/found
mkdir -p "$WORK" "$FOUND"
rm -f "$FOUND/INDEX"

pass=0; fail=0; err=0
for ((s = SEED; s < SEED + N; s++)); do
  NAME="rand_ssa_stress_$s"
  SV="$WORK/$NAME.sv"
  $GEN --features ssa_stress --emit-only --seed $s > "$SV"
  PAT=$(head -1 "$SV" | grep -oE "ssa_stress/[a-z_]+" | sed 's|ssa_stress/||')
  PAT=${PAT:-unknown}
  LOG="$WORK/$NAME.miter.log"

  if $MITER "$NAME" "$SV" >"$LOG" 2>&1; then
    if grep -q "FORMALLY EQUIVALENT" "$LOG"; then
      pass=$((pass+1))
      continue
    fi
  fi

  # Failed: copy artefacts + a one-line reason to INDEX.
  fail=$((fail+1))
  cp "$SV"  "$FOUND/${NAME}.sv"
  cp "$LOG" "$FOUND/${NAME}.miter.log"
  last=$(tail -30 "$LOG" | grep -E "NOT EQUIV|differ|Fatal|Error|Sort" | head -1)
  [ -z "$last" ] && last="(see ${NAME}.miter.log)"
  printf "seed=%d %-12s FAIL  %s\n" $s "$PAT" "$last" >> "$FOUND/INDEX"
  printf "  ❌ seed=%d %s — %s\n" $s "$PAT" "$last"
done

echo
echo "── $pass passed / $fail failed / $err gen-error / $N total ──"
[ -s "$FOUND/INDEX" ] && echo "    saved to $FOUND/"
[ "$fail" = 0 ] && [ "$err" = 0 ]
