/* Generated by Yosys 0.64+176 (git sha1 ca8886890, clang++ 18.1.8 -fPIC -O3) */

module and8(a, b, y);
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  output [7:0] y;
  wire [7:0] y;
  _AND_ _0_ (
    .A(a[6]),
    .B(b[6]),
    .Y(y[6])
  );
  _AND_ _1_ (
    .A(a[5]),
    .B(b[5]),
    .Y(y[5])
  );
  _AND_ _2_ (
    .A(a[4]),
    .B(b[4]),
    .Y(y[4])
  );
  _AND_ _3_ (
    .A(a[3]),
    .B(b[3]),
    .Y(y[3])
  );
  _AND_ _4_ (
    .A(a[2]),
    .B(b[2]),
    .Y(y[2])
  );
  _AND_ _5_ (
    .A(a[1]),
    .B(b[1]),
    .Y(y[1])
  );
  _AND_ _6_ (
    .A(a[0]),
    .B(b[0]),
    .Y(y[0])
  );
  _AND_ _7_ (
    .A(a[7]),
    .B(b[7]),
    .Y(y[7])
  );
endmodule
