/* Generated by Yosys 0.64+176 (git sha1 ca8886890, clang++ 18.1.8 -fPIC -O3) */

module counter(c, r, en, q);
  input c;
  wire c;
  input r;
  wire r;
  input en;
  wire en;
  output [3:0] q;
  wire [3:0] q;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  _NAND_ _07_ (
    .A(q[0]),
    .B(en),
    .Y(_04_)
  );
  _ANDNOT_ _08_ (
    .A(q[1]),
    .B(_04_),
    .Y(_05_)
  );
  _NAND_ _09_ (
    .A(q[2]),
    .B(_05_),
    .Y(_06_)
  );
  _XOR_ _10_ (
    .A(q[2]),
    .B(_05_),
    .Y(_00_)
  );
  _XNOR_ _11_ (
    .A(q[1]),
    .B(_04_),
    .Y(_01_)
  );
  _XOR_ _12_ (
    .A(q[0]),
    .B(en),
    .Y(_02_)
  );
  _XNOR_ _13_ (
    .A(q[3]),
    .B(_06_),
    .Y(_03_)
  );
  _DFF_PP0_ _14_ (
    .C(c),
    .D(_02_),
    .Q(q[0]),
    .R(r)
  );
  _DFF_PP0_ _15_ (
    .C(c),
    .D(_01_),
    .Q(q[1]),
    .R(r)
  );
  _DFF_PP0_ _16_ (
    .C(c),
    .D(_00_),
    .Q(q[2]),
    .R(r)
  );
  _DFF_PP0_ _17_ (
    .C(c),
    .D(_03_),
    .Q(q[3]),
    .R(r)
  );
endmodule
