/* Generated by Yosys 0.64+176 (git sha1 ca8886890, clang++ 18.1.8 -fPIC -O3) */

module full_adder(a, b, cin, sum, cout);
  input a;
  wire a;
  input b;
  wire b;
  input cin;
  wire cin;
  output sum;
  wire sum;
  output cout;
  wire cout;
  wire _0_;
  wire _1_;
  wire _2_;
  _NOT_ _3_ (
    .A(cin),
    .Y(_0_)
  );
  _NAND_ _4_ (
    .A(a),
    .B(b),
    .Y(_1_)
  );
  _XNOR_ _5_ (
    .A(a),
    .B(b),
    .Y(_2_)
  );
  _XNOR_ _6_ (
    .A(cin),
    .B(_2_),
    .Y(sum)
  );
  _OAI3_ _7_ (
    .A(_0_),
    .B(_2_),
    .C(_1_),
    .Y(cout)
  );
endmodule
