print("route_check: " .. svd.route_check("recipes/xil_selftest/routed_broken.json"))
impl = svd.read_nextpnr_json("recipes/xil_selftest/routed_broken.json")
impl = svd.augment_xil_models(impl)
spec = svd.parse("verible-ext", "top", {"/Users/jonathan/nextpnr-xilinx/xilinx/examples/counter25/top.v"})
spec = svd.augment_xil_models(spec)
print("VERDICT: " .. svd.miter(svd.pick(spec,"top"), svd.pick(impl,"top")))
