(* #100 — Cell-mapped Verilog emitter.

   Takes a [Lib_map.netlist] (the output of [Lib_map.map_circuit])
   and writes structural Verilog that ORFS's [read_verilog] step
   can ingest as the [1_synth.v] post-techmap netlist.

   Output is conservative ORFS-flavour Verilog:
     module <name> (port_list);
       input ...;
       output ...;
       wire ...;
       <cell> <inst> ( .pin(net), ... );  // many
       assign <lhs> = <expr>;             // for unmapped subtrees
     endmodule

   The unmapped-subtree assigns are deliberate: yosys's later
   techmap pass on the same file will pick them up and emit cells
   for the operators (+, -, *, ==, <).  We bound the work by
   only emitting raw operators we can express; everything else
   must be a cell. *)

let port_decl prefix name width =
  if width = 1 then Printf.sprintf "    %s %s;\n" prefix name
  else Printf.sprintf "    %s [%d:0] %s;\n" prefix (width - 1) name

let format_inst (i : Lib_map.instance) =
  let pin_strs = List.map (fun (c : Lib_map.pin_conn) ->
    Printf.sprintf ".%s(%s)" c.pin c.net) i.conns in
  Printf.sprintf "    %s %s ( %s );\n"
    i.cell.cell_name i.inst_name (String.concat ", " pin_strs)

(* Sanitise raw Verilog identifiers — hardcaml emits names like
   "_8" which are valid Verilog, plus name strings from the BIR.
   ORFS occasionally trips on bare leading underscores at the
   port declaration level; if so we'd add quoting here.  No
   transform needed today. *)
let sanitize n = n

let emit_module ~oc ~module_name (n : Lib_map.netlist) =
  let p fmt = Printf.fprintf oc fmt in
  p "/* Auto-generated by sv_decompiler / Lib_map / Cell_verilog_emit. */\n";
  p "/* Cell-mapped structural Verilog for ORFS [1_synth.v]. */\n\n";

  (* Port list *)
  p "module %s (\n" module_name;
  let port_names = List.map fst n.inputs @ List.map fst n.outputs in
  let port_strs = List.map sanitize port_names in
  let n_ports = List.length port_strs in
  List.iteri (fun i s ->
    Printf.fprintf oc "    %s%s\n" s (if i = n_ports - 1 then "" else ",")) port_strs;
  p ");\n\n";

  (* Declarations *)
  List.iter (fun (n, w) -> output_string oc (port_decl "input " (sanitize n) w)) n.inputs;
  List.iter (fun (n, w) -> output_string oc (port_decl "output" (sanitize n) w)) n.outputs;
  let dedup_wires =
    let seen = Hashtbl.create 64 in
    List.filter (fun (n, _) ->
      if Hashtbl.mem seen n then false
      else (Hashtbl.add seen n (); true)) n.wires in
  List.iter (fun (n, w) -> output_string oc (port_decl "wire  " (sanitize n) w)) dedup_wires;
  p "\n";

  (* Cell instances *)
  List.iter (fun i -> output_string oc (format_inst i)) n.insts;
  if n.insts <> [] then p "\n";

  (* Pass-through assigns for unmapped operators *)
  List.iter (fun (lhs, rhs) ->
    Printf.fprintf oc "    assign %s = %s;\n" (sanitize lhs) rhs)
    n.assigns;

  p "\nendmodule\n"

let emit_to_file ~module_name (n : Lib_map.netlist) path =
  let oc = open_out path in
  emit_module ~oc ~module_name n;
  close_out oc;
  path

(* Convenience: take a hardcaml [Circuit.t], lib-map it, emit it. *)
let emit_circuit ~module_name circuit path =
  let netlist = Lib_map.map_circuit circuit in
  emit_to_file ~module_name netlist path

(* ── Stats helpers ───────────────────────────────────────────── *)

let cell_histogram (n : Lib_map.netlist) =
  let h = Hashtbl.create 16 in
  List.iter (fun (i : Lib_map.instance) ->
    let cur = try Hashtbl.find h i.cell.cell_name with Not_found -> 0 in
    Hashtbl.replace h i.cell.cell_name (cur + 1)) n.insts;
  let pairs = Hashtbl.fold (fun k v acc -> (k, v) :: acc) h [] in
  List.sort (fun (_, a) (_, b) -> compare b a) pairs

let summary (n : Lib_map.netlist) =
  Printf.sprintf
    "  inputs    : %d\n  outputs   : %d\n  wires     : %d\n  cells     : %d\n  assigns   : %d (raw ops yosys techmaps)\n  cell mix  : %s\n"
    (List.length n.inputs)
    (List.length n.outputs)
    (List.length n.wires)
    (List.length n.insts)
    (List.length n.assigns)
    (String.concat ", "
       (List.map (fun (k, v) -> Printf.sprintf "%s=%d" k v)
          (cell_histogram n)))
