(executables
 (names sv_main_unified)
 (modules sv_ast sv_gen sv_gen_struct sv_gen_yosys sv_gen_hardcaml
          sv_main_unified sv_parse sv_transform sv_tran_struct
          behavioural_to_opt_ir opt_ir_to_sv sv_opt_ir
          sv_verify_hardcaml sv_memory sv_liberty)
 (libraries str yojson unix hardcaml z3)
 (preprocess (pps ppx_deriving_yojson)))

(env
  (dev
    (flags (:standard -g -w -16 -w -32 -w -52 -w -21 -w -26 -w -27 -w -37 -w -11 -w -9 -w -39))
  )
)
