(* Example: Counter module generated by sv_gen_hardcaml.ml
   Shows proper HardCaml idioms based on Input_hardcaml.ml approach *)
open Hardcaml
open Signal
open Always

(* Input interface *)
module I = struct
  type 'a t = {
    clock : 'a; [@bits 1]
    reset : 'a; [@bits 1]
    enable : 'a; [@bits 1]
  } [@@deriving sexp_of, hardcaml]
end

(* Output interface *)
module O = struct
  type 'a t = {
    count : 'a; [@bits 8]
    overflow : 'a; [@bits 1]
  } [@@deriving sexp_of, hardcaml]
end

(* Create function - direct Signal/Always API *)
let create scope (i : _ I.t) =
  let open Signal in
  let open Always in

  (* Internal signals and variables *)
  let count_var = Variable.reg ~enable:i.enable 
    (Reg_spec.create ~clock:i.clock ~reset:i.reset ()) ~width:8 in
  let overflow_var = Variable.wire ~default:(zero 1) in

  (* Combinational logic *)
  let next_count = count_var.value +:. 1 in
  let will_overflow = count_var.value ==:. 255 in

  (* Sequential always block *)
  compile [
    count_var <== mux2 i.enable next_count count_var.value;
    overflow_var <-- will_overflow;
  ];

  (* Build output record *)
  O.{
    count = count_var.value;
    overflow = overflow_var.value
  }

(* Helper to instantiate as Circuit *)
let circuit ~name =
  let module Circuit = Circuit.With_interface(I)(O) in
  Circuit.create_exn ~name (create (Scope.create ()))

(* Example usage in simulation *)
let sim_example () =
  let circ = circuit ~name:"counter" in
  let sim = Cyclesim.create circ in
  let inputs = Cyclesim.inputs sim in
  let outputs = Cyclesim.outputs sim in
  
  (* Initialize *)
  inputs.clock := Bits.vdd;
  inputs.reset := Bits.vdd;
  inputs.enable := Bits.gnd;
  Cyclesim.cycle sim;
  
  (* Run *)
  inputs.reset := Bits.gnd;
  inputs.enable := Bits.vdd;
  
  for i = 0 to 10 do
    Cyclesim.cycle sim;
    Printf.printf "Count: %d, Overflow: %d\n"
      (Bits.to_int !(outputs.count))
      (Bits.to_int !(outputs.overflow))
  done

(* Example with case statement - showing Always.switch usage *)
module FSM_Example = struct
  module I = struct
    type 'a t = {
      clock : 'a; [@bits 1]
      reset : 'a; [@bits 1]
      start : 'a; [@bits 1]
    } [@@deriving sexp_of, hardcaml]
  end

  module O = struct
    type 'a t = {
      state : 'a; [@bits 2]
      done_ : 'a; [@bits 1]
    } [@@deriving sexp_of, hardcaml]
  end

  let create scope (i : _ I.t) =
    let open Signal in
    let open Always in

    let state_var = Variable.reg 
      (Reg_spec.create ~clock:i.clock ~reset:i.reset ()) ~width:2 in
    let done_var = Variable.wire ~default:(zero 1) in

    (* State machine using switch *)
    compile [
      switch state_var.value [
        of_int ~width:2 0, [  (* IDLE *)
          when_ i.start [
            state_var <-- of_int ~width:2 1;
          ];
          done_var <-- gnd;
        ];
        of_int ~width:2 1, [  (* RUN *)
          state_var <-- of_int ~width:2 2;
          done_var <-- gnd;
        ];
        of_int ~width:2 2, [  (* FINISH *)
          state_var <-- of_int ~width:2 0;
          done_var <-- vdd;
        ];
        of_int ~width:2 3, [  (* ERROR *)
          state_var <-- of_int ~width:2 0;
          done_var <-- gnd;
        ];
      ];
    ];

    O.{
      state = state_var.value;
      done_ = done_var.value
    }
end

(* Example with signed arithmetic - following Input_hardcaml.ml patterns *)
module Signed_ALU = struct
  module I = struct
    type 'a t = {
      a : 'a; [@bits 8]
      b : 'a; [@bits 8]
      op : 'a; [@bits 2]  (* 0=add, 1=sub, 2=mul, 3=compare *)
    } [@@deriving sexp_of, hardcaml]
  end

  module O = struct
    type 'a t = {
      result : 'a; [@bits 8]
      negative : 'a; [@bits 1]
    } [@@deriving sexp_of, hardcaml]
  end

  let create scope (i : _ I.t) =
    let open Signal in
    let open Signed in

    (* Convert to signed *)
    let a_signed = of_signal i.a in
    let b_signed = of_signal i.b in

    (* Operations *)
    let add_result = a_signed +: b_signed in
    let sub_result = a_signed -: b_signed in
    let mul_result = a_signed *: b_signed in
    let cmp_result = a_signed <: b_signed in

    (* Select based on op *)
    let result = mux i.op [
      select (to_signal add_result) 0 8;
      select (to_signal sub_result) 0 8;
      select (to_signal mul_result) 0 8;
      uresize (to_signal cmp_result) 8;
    ] in

    let negative = bit result 7 in

    O.{
      result;
      negative
    }
end

(* Key differences from intermediate compilation approach:
   
   1. Direct Signal/Always API - no intermediate AST
   2. Use Variable.reg/wire with Reg_spec for registers
   3. Use compile [list of assignments] for always blocks
   4. Use switch for case statements with (value, actions) pairs
   5. Signed arithmetic via Signed.of_signal/to_signal
   6. No separate compilation phase - all done in create function
   
   This follows the pattern from Input_hardcaml.ml which:
   - Declares variables upfront
   - Builds Signal expressions directly
   - Uses compile to finalize assignments
   - Returns output record with .value accessors
*)
