(* Source_text_verible_json.ml - Add JSON deriving to Verible token type *)

(* Import the generated token type *)
type token = Source_text_verible.token =
  | Zi_zp
  | Zi_zd
  | Zi_np
  | Zi_nd
  | Xor
  | Xnor
  | Wreal
  | Wor
  | Wone
  | Within
  | With_LPAREN_covergroup_RPAREN
  | With
  | Wire
  | Wildcard
  | White_noise
  | While
  | Weak1
  | Weak0
  | Weak
  | Wand
  | Wait_order
  | Wait
  | Void
  | Virtual
  | Vectored
  | Var
  | VBAR_VBAR
  | VBAR_HYPHEN_GT
  | VBAR_EQ_GT
  | VBAR_EQ
  | VBAR
  | Uwire
  | Use
  | Untyped
  | Until_with
  | Until
  | Unsigned
  | Units
  | Unique_index
  | Unique0
  | Unique
  | Union
  | UNDERSCORE
  | Typedef
  | Type_option
  | Type
  | Trireg
  | Trior
  | Triand
  | Tri1
  | Tri0
  | Tri
  | Transition
  | Tranif1
  | Tranif0
  | Tran
  | Timeunit_check
  | Timeunit
  | Timeprecision_check
  | Timeprecision
  | Time
  | Throughout
  | This
  | Task
  | Tagged
  | Table
  | TUPLE9 of (token*token*token*token*token*token*token*token*token)
  | TUPLE8 of (token*token*token*token*token*token*token*token)
  | TUPLE7 of (token*token*token*token*token*token*token)
  | TUPLE6 of (token*token*token*token*token*token)
  | TUPLE5 of (token*token*token*token*token)
  | TUPLE4 of (token*token*token*token)
  | TUPLE3 of (token*token*token)
  | TUPLE2 of (token*token)
  | TUPLE15 of (token*token*token*token*token*token*token*token*token*token*token*token*token*token*token)
  | TUPLE14 of (token*token*token*token*token*token*token*token*token*token*token*token*token*token)
  | TUPLE13 of (token*token*token*token*token*token*token*token*token*token*token*token*token)
  | TUPLE12 of (token*token*token*token*token*token*token*token*token*token*token*token)
  | TUPLE11 of (token*token*token*token*token*token*token*token*token*token*token)
  | TUPLE10 of (token*token*token*token*token*token*token*token*token*token)
  | TLIST of (token list)
  | TK_edge_descriptor
  | TK_XZDigits
  | TK_UnBasedNumber of (string)
  | TK_TimeLiteral
  | TK_StringLiteral of (string)
  | TK_RealTime of (string)
  | TK_RS_EQ
  | TK_RSS_EQ
  | TK_OctDigits of (string)
  | TK_OctBase of (string)
  | TK_OTHER
  | TK_LS_EQ
  | TK_HexDigits of (string)
  | TK_HexBase of (string)
  | TK_EvalStringLiteral
  | TK_DecNumber of (string)
  | TK_DecDigits of (string)
  | TK_DecBase of (string)
  | TK_BinDigits of (string)
  | TK_BinBase of (string)
  | TK_AngleBracketInclude
  | TILDE_VBAR
  | TILDE_CARET
  | TILDE_AMPERSAND
  | TILDE
  | SystemTFIdentifier of (string)
  | Sync_reject_on
  | Sync_accept_on
  | SymbolIdentifier of (string)
  | Supply1
  | Supply0
  | Super
  | Sum
  | Struct
  | Strong1
  | Strong0
  | Strong
  | String
  | Static
  | Specparam
  | Specify
  | Sort
  | Solve
  | Soft
  | Small
  | Signed
  | Shuffle
  | Showcancelled
  | Shortreal
  | Shortint
  | Sequence
  | Scalared
  | Sample
  | S_until_with
  | S_until
  | S_nexttime
  | S_eventually
  | S_always
  | STRING of (string)
  | STAR_STAR
  | STAR_RPAREN
  | STAR_GT
  | STAR_EQ
  | STAR
  | SLIST of (string list)
  | SLASH_SLASH_end_of_line_comment
  | SLASH_EQ
  | SLASH_AMPERSAND_lowast_SEMICOLON_comment_AMPERSAND_lowast_SEMICOLON_SLASH
  | SLASH
  | SEMICOLON_LPAREN_after_HYPHEN_assertion_HYPHEN_variable_HYPHEN_decls_RPAREN
  | SEMICOLON
  | Rtranif1
  | Rtranif0
  | Rtran
  | Rsort
  | Rpmos
  | Rnmos
  | Reverse
  | Return
  | Restrict
  | Resolveto
  | Repeat
  | Release
  | Reject_on
  | Reg
  | Ref
  | Realtime
  | Real
  | Rcmos
  | Randsequence
  | Randomize
  | Randcase
  | Randc
  | Rand
  | RPAREN
  | RBRACK
  | RBRACE
  | QUOTE_LBRACE
  | QUOTE
  | QUERY
  | Pure
  | Pulsestyle_onevent
  | Pulsestyle_ondetect
  | Pullup
  | Pulldown
  | Pull1
  | Pull0
  | Protected
  | Property
  | Program
  | Product
  | Priority
  | Primitive
  | Pow
  | Potential
  | Posedge
  | Pmos
  | Paramset
  | Parameter
  | Packed
  | Package
  | PP_Identifier
  | PLUS_PLUS
  | PLUS_EQ
  | PLUS_COLON
  | PLUS
  | PLING_EQ_QUERY
  | PLING_EQ_EQ
  | PLING_EQ
  | PLING
  | PERCENT_EQ
  | PERCENT
  | Output
  | Or
  | Option
  | Null
  | Notif1
  | Notif0
  | Not
  | Noshowcancelled
  | Nor
  | Noise_table
  | Nmos
  | Nexttime
  | New
  | Nettype
  | Net_resolution
  | Negedge
  | Nature
  | Nand
  | NUMBER_step
  | Module
  | Modport
  | Min
  | Medium
  | Max
  | Matches
  | Macromodule
  | MacroNumericWidth
  | MacroIdentifier
  | MacroIdItem
  | MacroCallId
  | MacroCallCloseToEndLine
  | MacroArg
  | Longint
  | Logic
  | Localparam
  | Local_COLON_COLON
  | Local
  | Limexp
  | Library
  | Liblist
  | Let
  | Less_than_TK_else
  | Last_crossing
  | Large
  | Laplace_zp
  | Laplace_zd
  | Laplace_np
  | Laplace_nd
  | LT_PLUS
  | LT_LT_space_GT_GT
  | LT_LT_filepath_GT_GT
  | LT_LT_default_HYPHEN_text_GT_GT
  | LT_LT_BACKSLASH_BACKSLASH_n_GT_GT
  | LT_LT_BACKSLASH_BACKSLASH_line_HYPHEN_cont_GT_GT
  | LT_LT_BACKQUOTE_define_HYPHEN_tokens_GT_GT
  | LT_LT
  | LT_HYPHEN_GT
  | LT_EQ
  | LPAREN_timescale_unit_RPAREN
  | LPAREN_STAR_attribute_STAR_RPAREN
  | LPAREN_STAR
  | LPAREN
  | LINEFEED
  | LESS
  | LBRACK_STAR_RBRACK
  | LBRACK_STAR
  | LBRACK_PLUS_RBRACK
  | LBRACK_HYPHEN_GT
  | LBRACK_EQ
  | LBRACK
  | LBRACE
  | Join_none
  | Join_any
  | Join
  | Intersect
  | Interface
  | Interconnect
  | Integer
  | Int
  | Instance
  | Inside
  | Input
  | Inout
  | Initial
  | Infinite
  | Inf
  | Include
  | Incdir
  | Import
  | Implies
  | Implements
  | Illegal_bins
  | Ignore_bins
  | Ifnone
  | Iff
  | If
  | Idt_nature
  | Highz1
  | Highz0
  | HYPHEN_HYPHEN
  | HYPHEN_GT_LPAREN_trigger_RPAREN
  | HYPHEN_GT_LPAREN_logical_HYPHEN_implies_RPAREN
  | HYPHEN_GT_LPAREN_constraint_HYPHEN_implies_RPAREN
  | HYPHEN_GT_GT
  | HYPHEN_GT
  | HYPHEN_EQ
  | HYPHEN_COLON
  | HYPHEN
  | HASH_HYPHEN_HASH
  | HASH_HASH
  | HASH_EQ_HASH
  | HASH
  | Global
  | Genvar
  | Generate
  | GT_GT_GT
  | GT_GT
  | GT_EQ
  | GREATER
  | Function
  | From
  | Forkjoin
  | Fork
  | Forever
  | Foreach
  | Force
  | For
  | Flow
  | Flicker_noise
  | First_match
  | Find_last_index
  | Find_last
  | Find_index
  | Find_first_index
  | Find_first
  | Find
  | Final
  | Extern
  | Extends
  | Export
  | Expect
  | Exclude
  | Eventually
  | Event
  | EscapedIdentifier
  | Error
  | Enum
  | Endtask
  | Endtable
  | Endspecify
  | Endsequence
  | Endproperty
  | Endprogram
  | Endprimitive
  | Endparamset
  | Endpackage
  | Endnature
  | Endmodule
  | Endinterface
  | Endgroup
  | Endgenerate
  | Endfunction
  | Enddiscipline
  | Endconnectrules
  | Endconfig
  | Endclocking
  | Endclass
  | Endchecker
  | Endcase
  | End_of_file
  | End
  | Else
  | Edge
  | ERROR_TOKEN
  | EQ_GT
  | EQ_EQ_QUERY
  | EQ_EQ_EQ
  | EQ_EQ
  | EQUALS
  | EOF_TOKEN
  | EMPTY_TOKEN
  | ELIST of (token list)
  | Driver_update
  | Domain
  | Do
  | Dist
  | Discrete
  | Discipline
  | Disable
  | Design
  | Defparam
  | Default
  | Deassign
  | Ddt_nature
  | DOUBLEQUOTE
  | DOT_STAR
  | DOT
  | DOLLAR
  | DLR_width
  | DLR_unit
  | DLR_timeskew
  | DLR_skew
  | DLR_setuphold
  | DLR_setup
  | DLR_root
  | DLR_removal
  | DLR_recrem
  | DLR_recovery
  | DLR_period
  | DLR_nochange
  | DLR_hold
  | DLR_fullskew
  | DLR_attribute
  | DEFAULT
  | Cross
  | Coverpoint
  | Covergroup
  | Cover
  | Continuous
  | Continue
  | Context
  | Constraint
  | Const
  | Connectrules
  | Connectmodule
  | Connect
  | Config
  | Cmos
  | Clocking
  | Class
  | Checker
  | Chandle
  | Cell
  | Casez
  | Casex
  | Case
  | COMMA
  | COLON_SLASH
  | COLON_EQ
  | COLON_COLON
  | COLON
  | CHAR
  | CARET_EQ
  | CARET
  | Byte
  | Bufif1
  | Bufif0
  | Buf
  | Break
  | Bit
  | Binsof
  | Bins
  | Bind
  | Begin
  | Before
  | BACKSLASH
  | BACKQUOTE_uselib
  | BACKQUOTE_undef
  | BACKQUOTE_unconnected_drive
  | BACKQUOTE_timescale
  | BACKQUOTE_suppress_faults
  | BACKQUOTE_resetall
  | BACKQUOTE_protect
  | BACKQUOTE_pragma
  | BACKQUOTE_nounconnected_drive
  | BACKQUOTE_nosuppress_faults
  | BACKQUOTE_include
  | BACKQUOTE_ifndef
  | BACKQUOTE_ifdef
  | BACKQUOTE_endprotect
  | BACKQUOTE_endif
  | BACKQUOTE_endcelldefine
  | BACKQUOTE_end_keywords
  | BACKQUOTE_enable_portfaults
  | BACKQUOTE_elsif
  | BACKQUOTE_else
  | BACKQUOTE_disable_portfaults
  | BACKQUOTE_delay_mode_zero
  | BACKQUOTE_delay_mode_unit
  | BACKQUOTE_delay_mode_path
  | BACKQUOTE_delay_mode_distributed
  | BACKQUOTE_define
  | BACKQUOTE_default_trireg_strength
  | BACKQUOTE_default_nettype
  | BACKQUOTE_default_decay_time
  | BACKQUOTE_celldefine
  | BACKQUOTE_begin_keywords
  | BACKQUOTE_UNDERSCORE_UNDERSCORE_UNDERSCORE_UNDERSCORE_verible_verilog_library_end____
  | BACKQUOTE_UNDERSCORE_UNDERSCORE_UNDERSCORE_UNDERSCORE_verible_verilog_library_begin____
  | BACKQUOTE_BACKQUOTE
  | BACKQUOTE
  | Automatic
  | Assume
  | Assign
  | Assert
  | And
  | Analysis
  | Analog
  | Always_latch
  | Always_ff
  | Always_comb
  | Always
  | Aliasparam
  | Alias
  | Access
  | Accept_on
  | Ac_stim
  | Abstol
  | Absdelay
  | AT_AT
  | AT
  | AMPERSAND_EQ
  | AMPERSAND_AMPERSAND_AMPERSAND
  | AMPERSAND_AMPERSAND
  | AMPERSAND
  | ACCEPT
[@@deriving yojson]
