(* sv_main_unified.ml - Unified main with command-line backend selection *)
open Sv_ast

let jsontree = ref (`String "")

(* Main translation function *)
let translate_tree_to_ast json_file =
  print_endline ("JSON: "^json_file);
  let json = match Yojson.Safe.from_file json_file with `Assoc lst -> `Assoc (List.rev lst) | oth -> oth in
  jsontree := json;
  Sv_parse.parse json

let asthash = Hashtbl.create 255
let tranhash = Hashtbl.create 255

(* Backend type *)
type backend =
  | Standard      (* Original sv_gen.ml *)
  | Structural    (* sv_gen_struct.ml - structural with primitives *)
  | Yosys         (* sv_gen_yosys.ml - Yosys compatible *)
  | HardCaml      (* NEW: HardCaml OCaml output *)

(* Parse backend from string *)
let parse_backend s =
  match String.lowercase_ascii s with
  | "standard" | "std" -> Standard
  | "structural" | "struct" -> Structural
  | "yosys" -> Yosys
  | "hardcaml" | "hc" -> HardCaml
  | _ -> failwith ("Unknown backend: " ^ s)

(* Generate output based on backend choice *)
let generate_output backend ast =
  match backend with
  | Standard ->
      let result = Sv_gen.generate_sv ast 0 in
      (result, [])
  | Structural ->
      (* Apply transformations first *)
      let transformed_ast = Sv_transform.transform ~verbose:false ast in
      let structural_ast, warnings = Sv_tran_struct.generate_structural_ast transformed_ast in
      let result = Sv_gen.generate_sv structural_ast 0 in
      let header = "// Generated by structural converter\n// Primitives defined in: structural_primitives.sv\n\n" in
      (header ^ result, warnings)
  | Yosys ->
      Sv_gen_yosys.generate_sv_with_warnings ast 0
  | HardCaml ->
      let transformed_ast = Sv_transform.transform ~verbose:false ast in
      let fd = open_out "dump.json" in output_string fd (Yojson.Safe.pretty_to_string (sv_node_to_yojson transformed_ast)); close_out fd;
      Sv_gen_hardcaml.generate_hardcaml_with_warnings transformed_ast 0


(* Get file extension for backend *)
let get_extension backend =
  match backend with
  | Standard | Structural | Yosys | HardCaml -> ".sv"
  (* All backends output SystemVerilog/Verilog *)

(* Verify generated output with Z3 *)
let verify_output original_json generated_sv =
  try
    (* Parse generated Verilog back to JSON *)
    Printf.fprintf stderr "  [Verify] Parsing generated Verilog...\n";

    (* Extract actual module name from the Verilog file content *)
    let ic = open_in generated_sv in
    let file_content = really_input_string ic (min 2000 (in_channel_length ic)) in
    close_in ic;

    let module_name =
      try
        let rex = Str.regexp "module[ \t]+\\([a-zA-Z_][a-zA-Z0-9_]*\\)" in
        let _ = Str.search_forward rex file_content 0 in
        Str.matched_group 1 file_content
      with Not_found ->
        (* Fallback to filename if module declaration not found *)
        Filename.chop_extension (Filename.basename generated_sv)
    in
    let gen_json = "obj_dir/V" ^ module_name ^ "_verify.tree.json" in

    (* Check if generated file uses structural primitives *)
    let contains_substring s sub =
      try
        let _ = Str.search_forward (Str.regexp_string sub) s 0 in true
      with Not_found -> false in
    let uses_primitives =
      contains_substring file_content "structural_primitives" ||
      contains_substring file_content "dff_en" ||
      contains_substring file_content "mux2" in

    let cmd = if uses_primitives then
      Printf.sprintf "verilator --json-only --dump-tree-json --json-only-output %s --top-module %s structural_primitives.sv %s 2>&1 > /dev/null"
        gen_json module_name generated_sv
    else
      Printf.sprintf "verilator --json-only --dump-tree-json --json-only-output %s --top-module %s %s 2>&1 > /dev/null"
        gen_json module_name generated_sv in
    let ret = Sys.command cmd in
    if ret <> 0 then begin
      Printf.fprintf stderr "  ✗ Verification FAILED: Could not parse generated Verilog\n";
      false
    end else begin
      (* Run Z3 verification *)
      Printf.fprintf stderr "  [Verify] Running Z3 equivalence check...\n";
      let orig_ast = translate_tree_to_ast original_json in
      let gen_ast = translate_tree_to_ast gen_json in

      match Sv_verify_hardcaml.check_equivalence orig_ast gen_ast with
      | true ->
          Printf.fprintf stderr "  ✓ Verification PASSED: Functionally equivalent\n";
          true
      | false ->
          Printf.fprintf stderr "  ✗ Verification FAILED: Not equivalent\n";
          false
    end
  with e ->
    Printf.fprintf stderr "  ✗ Verification EXCEPTION: %s\n" (Printexc.to_string e);
    false

(* Scan directory and process all files *)
let scan output_dir backend verify =
  let obj = "obj_dir/" in
  (try Unix.mkdir output_dir 0o750 with e -> Printf.eprintf "%s: %s\n" output_dir (Printexc.to_string e));
  let lst = ref [] in
  let fd = Unix.opendir obj in
  (try while true do
       let f = Unix.readdir(fd) in
       (* Only process main tree.json files, not intermediate passes like *_NNN_*.tree.json *)
       (* Intermediate files have _NNN_ patterns where NNN is exactly 3 digits *)
       (* Also skip verification output files that end with _verify.tree.json *)
       let is_intermediate =
         try
           let rex = Str.regexp "_[0-9][0-9][0-9]_" in
           Str.string_match rex f 0 || Str.search_forward rex f 0 >= 0
         with Not_found -> false in
       let is_verify_output = Filename.check_suffix f "_verify.tree.json" in
       if f.[0]<>'.' && Filename.check_suffix f ".tree.json" && not is_intermediate && not is_verify_output then
         lst := f :: !lst;
       done with End_of_file -> Unix.closedir fd);

  (* Track statistics *)
  let total_files = List.length !lst in
  let successful = ref 0 in
  let failed = ref 0 in
  let verified = ref 0 in
  let verify_failed = ref 0 in

  (* Open warnings file *)
  let warnings_file = output_dir ^ "warnings.txt" in
  let warnings_fd = open_out warnings_file in

  Printf.printf "Processing %d files with backend: %s%s\n\n" total_files
    (match backend with
     | Standard -> "Standard"
     | Structural -> "Structural"
     | Yosys -> "Yosys"
     | HardCaml -> "HardCaml")
    (if verify then " (with verification)" else "");

  List.iter (fun itm ->
    Printf.fprintf stderr "Processing %s...\n" itm;
    try
      let ast = translate_tree_to_ast (obj^itm) in
      Hashtbl.add asthash itm ast;

      (* Generate with selected backend *)
      let (result, warnings) = generate_output backend ast in

      (* Write output *)
      let ext = get_extension backend in
      let out_file = output_dir ^ "decompile_" ^ itm ^ ext in
      let fd = open_out out_file in
      output_string fd result;
      close_out fd;

      (* Write warnings for this file *)
      if List.length warnings > 0 then begin
        Printf.fprintf warnings_fd "\n=== %s ===\n" itm;
        List.iter (fun w -> Printf.fprintf warnings_fd "  WARNING: %s\n" w) warnings;
        Printf.fprintf stderr "  %d warnings generated\n" (List.length warnings)
      end else begin
        Printf.fprintf stderr "  Success\n"
      end;

      (* Run verification if requested *)
      if verify then begin
        if verify_output (obj^itm) out_file then
          incr verified
        else
          incr verify_failed
      end;

      incr successful
    with
    | Failure msg ->
        Printf.eprintf "  ✗ FAILED: %s\n" msg;
        incr failed
    | e ->
        Printf.eprintf "  ✗ EXCEPTION: %s\n" (Printexc.to_string e);
        incr failed
  ) !lst;

  close_out warnings_fd;

  (* Print summary *)
  Printf.printf "\n========================================\n";
  Printf.printf "Conversion Summary\n";
  Printf.printf "========================================\n";
  Printf.printf "Total files:  %d\n" total_files;
  Printf.printf "Successful:   %d\n" !successful;
  Printf.printf "Failed:       %d\n" !failed;
  if verify then begin
    Printf.printf "Verified:     %d\n" !verified;
    Printf.printf "Verify failed:%d\n" !verify_failed;
  end;
  Printf.printf "========================================\n";
  if !successful > 0 then
    Printf.printf "\nWarnings written to: %s\n" warnings_file

(* Process single file *)
let process_single_file json_file output_file backend =
  Printf.fprintf stderr "Processing %s with backend: %s\n" json_file
    (match backend with 
     | Standard -> "Standard" 
     | Structural -> "Structural" 
     | Yosys -> "Yosys"
     | HardCaml -> "HardCaml");
  let ast = translate_tree_to_ast json_file in
  let (result, warnings) = generate_output backend ast in
  
  (* Write output *)
  let fd = open_out output_file in
  output_string fd result;
  close_out fd;
  
  (* Print warnings *)
  if List.length warnings > 0 then begin
    Printf.fprintf stderr "\n=== WARNINGS ===\n";
    List.iter (fun w -> Printf.fprintf stderr "  WARNING: %s\n" w) warnings;
    Printf.fprintf stderr "\nTotal: %d warnings\n" (List.length warnings)
  end else begin
    Printf.fprintf stderr "Success - no warnings\n"
  end;
  Printf.fprintf stderr "Output written to: %s\n" output_file

(* Verify two JSON files for equivalence *)
let verify_files original_json hardcaml_json =
  if not (Sys.file_exists original_json) then begin
    Printf.eprintf "Error: File not found: %s\n" original_json;
    exit 1
  end;

  if not (Sys.file_exists hardcaml_json) then begin
    Printf.eprintf "Error: File not found: %s\n" hardcaml_json;
    exit 1
  end;

  try
    Printf.fprintf stderr "Verifying equivalence:\n";
    Printf.fprintf stderr "  Original: %s\n" original_json;
    Printf.fprintf stderr "  HardCaml: %s\n\n" hardcaml_json;

    let result = Sv_verify_hardcaml.verify_hardcaml_output original_json hardcaml_json in
    exit (if result then 0 else 1)
  with
  | Failure msg ->
      Printf.eprintf "Error: %s\n" msg;
      exit 1
  | e ->
      Printf.eprintf "Error: %s\n" (Printexc.to_string e);
      Printexc.print_backtrace stderr;
      exit 1

(* SystemVerilog verification through both Yosys and Verilator *)
let verify_sv_yosys_verilator sv_file =
  if not (Sys.file_exists sv_file) then begin
    Printf.eprintf "Error: File not found: %s\n" sv_file;
    exit 1
  end;

  Printf.printf "=== SystemVerilog Verification (Yosys vs Verilator) ===\n\n";
  Printf.printf "Input file: %s\n\n" sv_file;

  (* Extract module name from file *)
  let module_name =
    try
      let ic = open_in sv_file in
      let file_content = really_input_string ic (min 2000 (in_channel_length ic)) in
      close_in ic;
      let rex = Str.regexp "module[ \t]+\\([a-zA-Z_][a-zA-Z0-9_]*\\)" in
      let _ = Str.search_forward rex file_content 0 in
      Str.matched_group 1 file_content
    with Not_found ->
      (* Fallback to filename *)
      Filename.chop_extension (Filename.basename sv_file)
  in

  Printf.printf "Module name: %s\n\n" module_name;

  (* Step 1: Run Yosys to generate RTLIL *)
  Printf.printf "Step 1: Running Yosys synthesis...\n";
  let rtlil_file = "obj_dir/" ^ module_name ^ ".il" in
  let yosys_cmd = Printf.sprintf
    "yosys -p 'read_verilog %s; hierarchy -check -top %s; proc; opt; write_rtlil %s' 2>&1 > /dev/null"
    sv_file module_name rtlil_file in

  let ret = Sys.command yosys_cmd in
  if ret <> 0 then begin
    Printf.eprintf "✗ Yosys failed to synthesize %s\n" sv_file;
    exit 1
  end;
  Printf.printf "✓ Yosys synthesis complete: %s\n\n" rtlil_file;

  (* Step 2: Run Verilator to generate tree JSON *)
  Printf.printf "Step 2: Running Verilator...\n";
  let json_file = "obj_dir/V" ^ module_name ^ ".tree.json" in
  let verilator_cmd = Printf.sprintf
    "verilator -Wno-fatal --json-only --dump-tree-json --json-only-output %s --top-module %s %s 2>&1 > /dev/null"
    json_file module_name sv_file in

  let ret = Sys.command verilator_cmd in
  if ret <> 0 then begin
    Printf.eprintf "✗ Verilator failed to parse %s\n" sv_file;
    exit 1
  end;
  Printf.printf "✓ Verilator parsing complete: %s\n\n" json_file;

  (* Step 3: Convert Yosys RTLIL to IR *)
  Printf.printf "Step 3: Converting Yosys RTLIL to IR...\n";
  let design = Sv_rtlil_reader.parse_rtlil_file rtlil_file in
  let yosys_ir_opt = Sv_rtlil_to_ir.rtlil_design_to_ir design in

  (match yosys_ir_opt with
   | None ->
       Printf.eprintf "✗ Failed to convert Yosys RTLIL to IR\n";
       exit 1
   | Some ir ->
       Printf.printf "✓ Yosys IR created\n";
       Sv_ir_verify.print_ir_stats ir);
  Printf.printf "\n";

  (* Step 4: Convert Verilator JSON to IR *)
  Printf.printf "Step 4: Converting Verilator JSON to IR...\n";
  let ast = translate_tree_to_ast json_file in
  let verilator_ir = Behavioural_to_opt_ir.convert ~verbose:false ast in
  Printf.printf "✓ Verilator IR created\n";
  Sv_ir_verify.print_ir_stats verilator_ir;
  Printf.printf "\n";

  (* Step 5: Verify equivalence with Z3 *)
  Printf.printf "Step 5: Verifying equivalence with Z3...\n";
  let yosys_ir = match yosys_ir_opt with Some ir -> ir | None -> assert false in
  let result = Sv_ir_verify.verify_ir_equivalence yosys_ir verilator_ir in
  Printf.printf "\n";

  if result then begin
    Printf.printf "✓ VERIFICATION PASSED\n";
    Printf.printf "  Yosys and Verilator produce equivalent results\n";
    Printf.printf "  The synthesis and behavioral paths are consistent\n";
    exit 0
  end else begin
    Printf.printf "✗ VERIFICATION FAILED\n";
    Printf.printf "  Yosys and Verilator produce different outputs\n";
    Printf.printf "  Counterexample found (see above)\n\n";

    (* Show IR comparison *)
    Printf.printf "IR Comparison:\n";
    let yosys_ir = match yosys_ir_opt with Some ir -> ir | None -> assert false in
    Printf.printf "  Yosys nodes: %d, Verilator nodes: %d\n"
      (Hashtbl.length yosys_ir.ir_nodes)
      (Hashtbl.length verilator_ir.ir_nodes);

    (* Suggest Verible as tie-breaker *)
    Printf.printf "\nNote: When Yosys and Verilator disagree, this could indicate:\n";
    Printf.printf "  1. Different IR representations of the same logic (false negative)\n";
    Printf.printf "  2. Width extension handling differences\n";
    Printf.printf "  3. An actual semantic difference (true positive)\n\n";
    Printf.printf "Suggestion: Use Verible as a third validator:\n";
    Printf.printf "  verible-verilog-syntax --printtree %s\n" sv_file;
    Printf.printf "  Or use the Verible parser in hardcaml-lua for formal analysis\n";
    exit 1
  end

(* Three-way SystemVerilog verification (Yosys + Verilator + Verible) *)
let verify_sv_3way sv_file =
  if not (Sys.file_exists sv_file) then begin
    Printf.eprintf "Error: File not found: %s\n" sv_file;
    exit 1
  end;

  Printf.printf "=== Three-Way SystemVerilog Verification ===\n\n";
  Printf.printf "Input file: %s\n\n" sv_file;

  (* Step 0: Validate syntax with Verible *)
  Printf.printf "Step 0: Validating syntax with Verible...\n";
  let verible_cmd = Printf.sprintf "verible-verilog-syntax %s 2>&1 > /dev/null" sv_file in
  let ret = Sys.command verible_cmd in
  if ret <> 0 then begin
    Printf.eprintf "✗ Verible syntax validation failed\n";
    Printf.eprintf "  The file may contain syntax errors\n";
    exit 1
  end;
  Printf.printf "✓ Verible syntax validation passed\n\n";

  (* Continue with Yosys vs Verilator verification *)
  verify_sv_yosys_verilator sv_file

(* RTLIL verification commands *)
let verify_rtlil_self rtlil_file =
  if not (Sys.file_exists rtlil_file) then begin
    Printf.eprintf "Error: File not found: %s\n" rtlil_file;
    exit 1
  end;

  Printf.printf "=== RTLIL Self-Verification ===\n\n";
  Printf.printf "File: %s\n\n" rtlil_file;

  (* Parse RTLIL *)
  Printf.printf "Step 1: Parsing RTLIL...\n";
  let design = Sv_rtlil_reader.parse_rtlil_file rtlil_file in
  Printf.printf "✓ Parsed successfully\n\n";

  (* Print summary *)
  Printf.printf "Step 2: Design Summary\n";
  Sv_rtlil_reader.print_rtlil_summary design;
  Printf.printf "\n";

  (* Convert to IR *)
  Printf.printf "Step 3: Converting to IR...\n";
  match Sv_rtlil_to_ir.rtlil_design_to_ir design with
  | None ->
      Printf.eprintf "✗ Failed to convert RTLIL to IR\n";
      exit 1
  | Some ir ->
      Printf.printf "✓ Converted to IR\n";
      Sv_ir_verify.print_ir_stats ir;
      Printf.printf "\n";

      (* Self-equivalence check *)
      Printf.printf "Step 4: Self-Equivalence Check\n";
      Printf.printf "Verifying IR against itself...\n";
      let result = Sv_ir_verify.verify_ir_equivalence ir ir in
      Printf.printf "\n";

      if result then begin
        Printf.printf "✓ VERIFICATION PASSED\n";
        Printf.printf "  The RTLIL design is internally consistent\n";
        Printf.printf "  All outputs verified equivalent to themselves\n";
        exit 0
      end else begin
        Printf.printf "✗ VERIFICATION FAILED\n";
        Printf.printf "  Internal inconsistency detected\n";
        exit 1
      end

let verify_rtlil_equiv rtlil_file1 rtlil_file2 =
  if not (Sys.file_exists rtlil_file1) then begin
    Printf.eprintf "Error: File not found: %s\n" rtlil_file1;
    exit 1
  end;
  if not (Sys.file_exists rtlil_file2) then begin
    Printf.eprintf "Error: File not found: %s\n" rtlil_file2;
    exit 1
  end;

  Printf.printf "=== RTLIL Equivalence Verification ===\n\n";
  Printf.printf "File 1: %s\n" rtlil_file1;
  Printf.printf "File 2: %s\n\n" rtlil_file2;

  (* Parse first RTLIL *)
  Printf.printf "Step 1: Parsing first RTLIL...\n";
  let design1 = Sv_rtlil_reader.parse_rtlil_file rtlil_file1 in
  Printf.printf "✓ Parsed successfully\n\n";

  (* Parse second RTLIL *)
  Printf.printf "Step 2: Parsing second RTLIL...\n";
  let design2 = Sv_rtlil_reader.parse_rtlil_file rtlil_file2 in
  Printf.printf "✓ Parsed successfully\n\n";

  (* Convert to IR *)
  Printf.printf "Step 3: Converting to IR...\n";
  let ir1_opt = Sv_rtlil_to_ir.rtlil_design_to_ir design1 in
  let ir2_opt = Sv_rtlil_to_ir.rtlil_design_to_ir design2 in

  match ir1_opt, ir2_opt with
  | Some ir1, Some ir2 ->
      Printf.printf "✓ Both designs converted to IR\n\n";

      Printf.printf "Design 1:\n";
      Sv_ir_verify.print_ir_stats ir1;
      Printf.printf "\nDesign 2:\n";
      Sv_ir_verify.print_ir_stats ir2;
      Printf.printf "\n";

      (* Verify equivalence *)
      Printf.printf "Step 4: Checking Equivalence\n";
      let result = Sv_ir_verify.verify_ir_equivalence ir1 ir2 in
      Printf.printf "\n";

      if result then begin
        Printf.printf "✓ DESIGNS ARE EQUIVALENT\n";
        Printf.printf "  Both RTLIL files produce identical outputs\n";
        exit 0
      end else begin
        Printf.printf "✗ DESIGNS ARE NOT EQUIVALENT\n";
        Printf.printf "  Counterexample found (see above)\n";
        exit 1
      end
  | None, _ ->
      Printf.eprintf "✗ Failed to convert first RTLIL to IR\n";
      exit 1
  | _, None ->
      Printf.eprintf "✗ Failed to convert second RTLIL to IR\n";
      exit 1

(* Print usage *)
let print_usage () =
  Printf.eprintf "SystemVerilog Decompiler - Unified Backend Selector\n\n";
  Printf.eprintf "Usage:\n";
  Printf.eprintf "  %s scan <backend> <output_dir> [--verify]\n" Sys.argv.(0);
  Printf.eprintf "      Process all files in obj_dir/\n";
  Printf.eprintf "      --verify: Run Z3 verification (all backends)\n\n";
  Printf.eprintf "  %s file <backend> <json_file> <output_file>\n" Sys.argv.(0);
  Printf.eprintf "      Process single file\n\n";
  Printf.eprintf "  %s verify <original.json> <hardcaml.json>\n" Sys.argv.(0);
  Printf.eprintf "      Verify equivalence between original and HardCaml output\n\n";
  Printf.eprintf "  %s verify-sv <file.v>\n" Sys.argv.(0);
  Printf.eprintf "      Verify SystemVerilog file by comparing Yosys and Verilator paths\n\n";
  Printf.eprintf "  %s verify-sv-3way <file.v>\n" Sys.argv.(0);
  Printf.eprintf "      Three-way verification: Verible syntax + Yosys + Verilator\n\n";
  Printf.eprintf "  %s verify-rtlil <file.il>\n" Sys.argv.(0);
  Printf.eprintf "      Verify RTLIL file (self-equivalence check)\n\n";
  Printf.eprintf "  %s verify-rtlil-equiv <file1.il> <file2.il>\n" Sys.argv.(0);
  Printf.eprintf "      Verify two RTLIL files are equivalent\n\n";
  Printf.eprintf "  %s interactive\n" Sys.argv.(0);
  Printf.eprintf "      Start interactive console mode\n";
  Printf.eprintf "      Provides REPL with all commands and shell access\n\n";
  Printf.eprintf "Backends:\n";
  Printf.eprintf "  standard, std      - Original SystemVerilog output\n";
  Printf.eprintf "  structural, struct - Structural with primitives\n";
  Printf.eprintf "  yosys              - Yosys-compatible output\n";
  Printf.eprintf "  hardcaml, hc       - HardCaml OCaml output\n\n";
  Printf.eprintf "Examples:\n";
  Printf.eprintf "  %s scan yosys results/\n" Sys.argv.(0);
  Printf.eprintf "  %s scan hardcaml results/ --verify\n" Sys.argv.(0);
  Printf.eprintf "  %s file hardcaml input.json output.ml\n" Sys.argv.(0);
  Printf.eprintf "  %s verify obj_dir/Valu.tree.json obj_dir/Valu_hardcaml.tree.json\n" Sys.argv.(0);
  Printf.eprintf "  %s interactive\n" Sys.argv.(0);
  exit 1

(* Interactive mode state *)
module Interactive = struct
  type state = {
    mutable loaded_asts: (string * sv_node) list;
    mutable current_backend: backend option;
    mutable current_dir: string;
    mutable running: bool;
    mutable history: string list;
  }

  let create_state () = {
    loaded_asts = [];
    current_backend = None;
    current_dir = Sys.getcwd ();
    running = true;
    history = [];
  }

  let print_banner () =
    Printf.printf "\n";
    Printf.printf "╔════════════════════════════════════════════════════════════╗\n";
    Printf.printf "║  SystemVerilog Decompiler - Interactive Console           ║\n";
    Printf.printf "║  Type 'help' for commands, 'quit' to exit                 ║\n";
    Printf.printf "╚════════════════════════════════════════════════════════════╝\n";
    Printf.printf "\n"

  let print_help () =
    Printf.printf "\nAvailable Commands:\n\n";
    Printf.printf "File Operations:\n";
    Printf.printf "  read_verilog <file.v> ...     Run Verilator on files and load result\n";
    Printf.printf "  load <file.json>              Load Verilator JSON into AST\n";
    Printf.printf "  list                          List all loaded ASTs\n";
    Printf.printf "  unload <name>                 Unload an AST from memory\n";
    Printf.printf "  clear                         Clear all loaded ASTs\n\n";
    Printf.printf "Backend Operations:\n";
    Printf.printf "  backend <name>                Set current backend (standard|structural|yosys|hardcaml)\n";
    Printf.printf "  backends                      List available backends\n";
    Printf.printf "  generate <ast> <output>       Generate output for loaded AST\n";
    Printf.printf "  scan <backend> <dir>          Process all files in obj_dir/\n\n";
    Printf.printf "Behavioral IR Commands:\n";
    Printf.printf "  test-verilator <json>         Test Verilator → Behavioral IR pipeline\n";
    Printf.printf "  test-equiv <vhdl> <sv>        Test VHDL vs SV behavioral equivalence\n";
    Printf.printf "  test-miter <vhdl> <sv>        Formal Z3 miter verification (VHDL ≡ SV)\n";
    Printf.printf "  test-z3-simple <vhdl> <sv>    Structural Z3 verification\n\n";
    Printf.printf "Verification:\n";
    Printf.printf "  verify <orig.json> <hc.json>  Verify equivalence between files\n\n";
    Printf.printf "Shell Operations:\n";
    Printf.printf "  !<command>                    Execute shell command\n";
    Printf.printf "  shell <command>               Execute shell command\n";
    Printf.printf "  cd <dir>                      Change directory\n";
    Printf.printf "  pwd                           Print working directory\n";
    Printf.printf "  ls [path]                     List directory contents\n\n";
    Printf.printf "Interactive:\n";
    Printf.printf "  help                          Show this help\n";
    Printf.printf "  history                       Show command history\n";
    Printf.printf "  quit, exit                    Exit interactive mode\n\n"

  let print_backends () =
    Printf.printf "\nAvailable Backends:\n";
    Printf.printf "  standard     - Original SystemVerilog output (clean, readable)\n";
    Printf.printf "  structural   - Structural with primitives (register inference, memory)\n";
    Printf.printf "  yosys        - Yosys-compatible output (open-source tools)\n";
    Printf.printf "  hardcaml     - HardCaml OCaml output (formal verification)\n\n"

  let execute_shell_command cmd =
    try
      let exit_code = Sys.command cmd in
      if exit_code <> 0 then
        Printf.printf "Shell command exited with code %d\n" exit_code
    with e ->
      Printf.printf "Error executing shell command: %s\n" (Printexc.to_string e)

  let load_ast state filename =
    try
      Printf.printf "Loading %s...\n" filename;
      let ast = translate_tree_to_ast filename in
      let name = Filename.basename filename in
      state.loaded_asts <- (name, ast) :: state.loaded_asts;
      Hashtbl.add asthash name ast;
      Printf.printf "✓ Loaded as '%s'\n" name
    with e ->
      Printf.printf "✗ Error loading file: %s\n" (Printexc.to_string e)

  let read_verilog state files =
    if List.length files = 0 then begin
      Printf.printf "✗ Usage: read_verilog <file.v> [file2.v ...]\n"
    end else begin
      try
        (* Extract module name from first file *)
        Printf.printf "Reading Verilog files: %s\n" (String.concat " " files);

        let first_file = List.hd files in
        let ic = open_in first_file in
        let file_content = really_input_string ic (in_channel_length ic) in
        close_in ic;

        let module_name =
          try
            let rex = Str.regexp "module[ \t]+\\([a-zA-Z_][a-zA-Z0-9_]*\\)" in
            let _ = Str.search_forward rex file_content 0 in
            Str.matched_group 1 file_content
          with Not_found ->
            (* Fallback to filename *)
            Filename.chop_extension (Filename.basename first_file)
        in

        Printf.printf "Detected top module: %s\n" module_name;

        (* Build verilator command *)
        let files_str = String.concat " " (List.map (fun f -> "\"" ^ f ^ "\"") files) in
        let json_output = "obj_dir/V" ^ module_name ^ ".tree.json" in
        let cmd = Printf.sprintf "verilator --json-only --quiet -Wno-fatal --top-module %s %s 2>&1"
          module_name files_str in

        Printf.printf "Running: verilator --json-only --top-module %s %s\n"
          module_name (String.concat " " files);

        let exit_code = Sys.command cmd in
        if exit_code <> 0 then begin
          Printf.printf "✗ Verilator failed with exit code %d\n" exit_code
        end else begin
          Printf.printf "✓ Verilator succeeded\n";

          (* Check if JSON file was created *)
          if Sys.file_exists json_output then begin
            Printf.printf "Generated: %s\n" json_output;
            (* Automatically load the result *)
            load_ast state json_output
          end else begin
            Printf.printf "✗ Expected output file not found: %s\n" json_output;
            Printf.printf "  Check obj_dir/ for generated files\n"
          end
        end
      with e ->
        Printf.printf "✗ Error: %s\n" (Printexc.to_string e)
    end

  let list_asts state =
    if List.length state.loaded_asts = 0 then
      Printf.printf "No ASTs loaded\n"
    else begin
      Printf.printf "\nLoaded ASTs:\n";
      List.iter (fun (name, _) ->
        Printf.printf "  • %s\n" name
      ) (List.rev state.loaded_asts)
    end

  let unload_ast state name =
    let found = List.exists (fun (n, _) -> n = name) state.loaded_asts in
    if found then begin
      state.loaded_asts <- List.filter (fun (n, _) -> n <> name) state.loaded_asts;
      Hashtbl.remove asthash name;
      Printf.printf "✓ Unloaded '%s'\n" name
    end else
      Printf.printf "✗ AST '%s' not found\n" name

  let clear_asts state =
    state.loaded_asts <- [];
    Hashtbl.clear asthash;
    Printf.printf "✓ Cleared all ASTs\n"

  let set_backend state backend_str =
    try
      let backend = parse_backend backend_str in
      state.current_backend <- Some backend;
      Printf.printf "✓ Backend set to: %s\n" backend_str
    with Failure msg ->
      Printf.printf "✗ %s\n" msg

  let generate_from_loaded state ast_name output_file =
    match state.current_backend with
    | None ->
        Printf.printf "✗ No backend set. Use 'backend <name>' first\n"
    | Some backend ->
        try
          let ast = List.assoc ast_name state.loaded_asts in
          Printf.printf "Generating output with %s backend...\n"
            (match backend with Standard -> "standard" | Structural -> "structural"
                              | Yosys -> "yosys" | HardCaml -> "hardcaml");
          let (result, warnings) = generate_output backend ast in
          let fd = open_out output_file in
          output_string fd result;
          close_out fd;
          if List.length warnings > 0 then begin
            Printf.printf "  %d warnings generated\n" (List.length warnings);
            List.iter (fun w -> Printf.printf "    WARNING: %s\n" w) warnings
          end;
          Printf.printf "✓ Output written to: %s\n" output_file
        with
        | Not_found ->
            Printf.printf "✗ AST '%s' not loaded. Use 'list' to see loaded ASTs\n" ast_name
        | e ->
            Printf.printf "✗ Error generating output: %s\n" (Printexc.to_string e)

  let change_directory state dir =
    try
      Sys.chdir dir;
      state.current_dir <- Sys.getcwd ();
      Printf.printf "✓ Changed to: %s\n" state.current_dir
    with e ->
      Printf.printf "✗ Error: %s\n" (Printexc.to_string e)

  let print_working_directory state =
    Printf.printf "%s\n" (Sys.getcwd ())

  let list_directory path =
    let dir = if path = "" then "." else path in
    try
      let files = Sys.readdir dir in
      Array.sort String.compare files;
      Array.iter (fun f ->
        let full_path = Filename.concat dir f in
        let is_dir = try Sys.is_directory full_path with _ -> false in
        if is_dir then
          Printf.printf "  [DIR]  %s/\n" f
        else
          Printf.printf "  [FILE] %s\n" f
      ) files
    with e ->
      Printf.printf "✗ Error: %s\n" (Printexc.to_string e)

  let show_history state =
    if List.length state.history = 0 then
      Printf.printf "No command history\n"
    else begin
      Printf.printf "\nCommand History:\n";
      List.iteri (fun i cmd ->
        Printf.printf "  %3d  %s\n" (i + 1) cmd
      ) (List.rev state.history)
    end

  let parse_command line =
    let line = String.trim line in
    if line = "" then
      []
    else
      (* Simple tokenizer - split on whitespace, respecting quotes *)
      let rec tokenize chars current tokens in_quote =
        match chars with
        | [] ->
            if current <> "" then
              List.rev (current :: tokens)
            else
              List.rev tokens
        | '"' :: rest ->
            tokenize rest current tokens (not in_quote)
        | ' ' :: rest when not in_quote ->
            if current <> "" then
              tokenize rest "" (current :: tokens) in_quote
            else
              tokenize rest "" tokens in_quote
        | c :: rest ->
            tokenize rest (current ^ String.make 1 c) tokens in_quote
      in
      tokenize (List.of_seq (String.to_seq line)) "" [] false

  let handle_command state tokens =
    match tokens with
    | [] -> ()
    | "help" :: _ -> print_help ()
    | "quit" :: _ | "exit" :: _ ->
        state.running <- false;
        Printf.printf "Goodbye!\n"
    | "history" :: _ -> show_history state
    | "read_verilog" :: files when List.length files > 0 -> read_verilog state files
    | "read_verilog" :: _ -> Printf.printf "✗ Usage: read_verilog <file.v> [file2.v ...]\n"
    | "load" :: filename :: _ -> load_ast state filename
    | "list" :: _ -> list_asts state
    | "unload" :: name :: _ -> unload_ast state name
    | "clear" :: _ -> clear_asts state
    | "backend" :: name :: _ -> set_backend state name
    | "backends" :: _ -> print_backends ()
    | "generate" :: ast_name :: output :: _ -> generate_from_loaded state ast_name output
    | "scan" :: backend_str :: dir :: rest ->
        let verify = List.mem "--verify" rest in
        (try
          let backend = parse_backend backend_str in
          let dir = if dir.[String.length dir - 1] = '/' then dir else dir ^ "/" in
          scan dir backend verify
        with Failure msg ->
          Printf.printf "✗ %s\n" msg)
    | "verify" :: orig :: hc :: _ ->
        verify_files orig hc
    | "test-verilator" :: json_file :: _ ->
        Printf.printf "Running: dune exec ./test_verilator_behavioral.exe %s\n" json_file;
        let cmd = Printf.sprintf "dune exec ./test_verilator_behavioral.exe %s" json_file in
        execute_shell_command cmd
    | "test-verilator" :: _ ->
        Printf.printf "✗ Usage: test-verilator <verilator.json>\n"
    | "test-equiv" :: vhdl :: sv :: _ ->
        Printf.printf "Running: dune exec ./test_behavioral_equivalence.exe %s %s\n" vhdl sv;
        let cmd = Printf.sprintf "dune exec ./test_behavioral_equivalence.exe %s %s" vhdl sv in
        execute_shell_command cmd
    | "test-equiv" :: _ ->
        Printf.printf "✗ Usage: test-equiv <file.vhd> <file.sv>\n"
    | "test-miter" :: vhdl :: sv :: _ ->
        Printf.printf "Running: dune exec ./test_miter_equivalence.exe %s %s\n" vhdl sv;
        let cmd = Printf.sprintf "dune exec ./test_miter_equivalence.exe %s %s" vhdl sv in
        execute_shell_command cmd
    | "test-miter" :: _ ->
        Printf.printf "✗ Usage: test-miter <file.vhd> <file.sv>\n"
    | "test-z3-simple" :: vhdl :: sv :: _ ->
        Printf.printf "Running: dune exec ./test_behavioral_z3_simple.exe %s %s\n" vhdl sv;
        let cmd = Printf.sprintf "dune exec ./test_behavioral_z3_simple.exe %s %s" vhdl sv in
        execute_shell_command cmd
    | "test-z3-simple" :: _ ->
        Printf.printf "✗ Usage: test-z3-simple <file.vhd> <file.sv>\n"
    | "cd" :: dir :: _ -> change_directory state dir
    | "pwd" :: _ -> print_working_directory state
    | "ls" :: rest ->
        let path = if rest = [] then "" else List.hd rest in
        list_directory path
    | "shell" :: rest ->
        let cmd = String.concat " " rest in
        execute_shell_command cmd
    | cmd :: _ when String.length cmd > 0 && cmd.[0] = '!' ->
        let shell_cmd = String.sub cmd 1 (String.length cmd - 1) in
        execute_shell_command shell_cmd
    | cmd :: _ ->
        Printf.printf "Unknown command: %s (type 'help' for available commands)\n" cmd

  let read_line_with_prompt prompt =
    Printf.printf "%s" prompt;
    flush stdout;
    try
      Some (read_line ())
    with End_of_file ->
      None

  let run () =
    let state = create_state () in
    print_banner ();

    while state.running do
      match read_line_with_prompt "sv> " with
      | None ->
          state.running <- false;
          Printf.printf "\n"
      | Some line when String.trim line <> "" ->
          state.history <- line :: state.history;
          let tokens = parse_command line in
          (try
            handle_command state tokens
          with e ->
            Printf.printf "✗ Error: %s\n" (Printexc.to_string e);
            Printexc.print_backtrace stdout)
      | Some _ -> ()
    done
end
(* Main entry point *)
let () =
  if Array.length Sys.argv < 2 then
    print_usage ()
  else begin
    let mode = Sys.argv.(1) in
    try
      match mode with
      | "scan" when Array.length Sys.argv >= 4 ->
          let backend = parse_backend Sys.argv.(2) in
          let output_dir = Sys.argv.(3) in
          let output_dir = if output_dir.[String.length output_dir - 1] = '/'
                          then output_dir else output_dir ^ "/" in
          (* Check for --verify flag *)
          let verify = Array.length Sys.argv >= 5 && Sys.argv.(4) = "--verify" in
          scan output_dir backend verify
      | "file" when Array.length Sys.argv >= 5 ->
          let backend = parse_backend Sys.argv.(2) in
          let json_file = Sys.argv.(3) in
          let output_file = Sys.argv.(4) in
          process_single_file json_file output_file backend
      | "verify" when Array.length Sys.argv >= 4 ->
          let original_json = Sys.argv.(2) in
          let hardcaml_json = Sys.argv.(3) in
          verify_files original_json hardcaml_json
      | "verify-sv" when Array.length Sys.argv >= 3 ->
          let sv_file = Sys.argv.(2) in
          verify_sv_yosys_verilator sv_file
      | "verify-sv-3way" when Array.length Sys.argv >= 3 ->
          let sv_file = Sys.argv.(2) in
          verify_sv_3way sv_file
      | "verify-rtlil" when Array.length Sys.argv >= 3 ->
          let rtlil_file = Sys.argv.(2) in
          verify_rtlil_self rtlil_file
      | "verify-rtlil-equiv" when Array.length Sys.argv >= 4 ->
          let rtlil_file1 = Sys.argv.(2) in
          let rtlil_file2 = Sys.argv.(3) in
          verify_rtlil_equiv rtlil_file1 rtlil_file2
      | "interactive" | "repl" | "i" ->
          Interactive.run ()
      | _ -> print_usage ()
    with
    | Failure msg ->
        Printf.eprintf "Error: %s\n" msg;
        exit 1
    | e ->
        Printf.eprintf "Error: %s\n" (Printexc.to_string e);
        exit 1
  end
