(* sv_main_unified.ml - Unified main with command-line backend selection *)
open Sv_ast

let jsontree = ref (`String "")

(* Main translation function *)
let translate_tree_to_ast json_file =
  print_endline ("JSON: "^json_file);
  let json = match Yojson.Safe.from_file json_file with `Assoc lst -> `Assoc (List.rev lst) | oth -> oth in
  jsontree := json;
  Sv_parse.parse json

let asthash = Hashtbl.create 255
let tranhash = Hashtbl.create 255

(* Backend type *)
type backend = 
  | Standard      (* Original sv_gen.ml *)
  | Structural    (* sv_gen_struct.ml - structural with primitives *)
  | Yosys         (* sv_gen_yosys.ml - Yosys compatible *)
  | HardCaml      (* NEW: HardCaml OCaml output *)

(* Generate output based on backend choice *)
let generate_output backend ast =
  match backend with
  | Standard ->
      let result = Sv_gen.generate_sv ast 0 in
      (result, [])
  | Structural ->
      (* Apply transformations first *)
      let transformed_ast = Sv_transform.transform ~verbose:false ast in
      let structural_ast, warnings = Sv_tran_struct.generate_structural_ast transformed_ast in
      let result = Sv_gen.generate_sv structural_ast 0 in
      let header = "// Generated by structural converter\n// Primitives defined in: structural_primitives.sv\n\n" in
      (header ^ result, warnings)
  | Yosys ->
      Sv_gen_yosys.generate_sv_with_warnings ast 0
  | HardCaml ->
      let transformed_ast = Sv_transform.transform ~verbose:false ast in
      let fd = open_out "dump.json" in output_string fd (Yojson.Safe.pretty_to_string (sv_node_to_yojson transformed_ast)); close_out fd;
      Sv_gen_hardcaml.generate_hardcaml_with_warnings transformed_ast 0

(* Get file extension for backend *)
let get_extension backend =
  match backend with
  | Standard | Structural | Yosys | HardCaml -> ".sv"
  (* All backends output SystemVerilog/Verilog *)

(* Verify generated output with Z3 *)
let verify_output original_json generated_sv =
  try
    (* Parse generated Verilog back to JSON *)
    Printf.fprintf stderr "  [Verify] Parsing generated Verilog...\n";

    (* Extract actual module name from the Verilog file content *)
    let ic = open_in generated_sv in
    let file_content = really_input_string ic (min 2000 (in_channel_length ic)) in
    close_in ic;

    let module_name =
      try
        let rex = Str.regexp "module[ \t]+\\([a-zA-Z_][a-zA-Z0-9_]*\\)" in
        let _ = Str.search_forward rex file_content 0 in
        Str.matched_group 1 file_content
      with Not_found ->
        (* Fallback to filename if module declaration not found *)
        Filename.chop_extension (Filename.basename generated_sv)
    in
    let gen_json = "obj_dir/V" ^ module_name ^ "_verify.tree.json" in

    (* Check if generated file uses structural primitives *)
    let contains_substring s sub =
      try
        let _ = Str.search_forward (Str.regexp_string sub) s 0 in true
      with Not_found -> false in
    let uses_primitives =
      contains_substring file_content "structural_primitives" ||
      contains_substring file_content "dff_en" ||
      contains_substring file_content "mux2" in

    let cmd = if uses_primitives then
      Printf.sprintf "verilator --json-only --dump-tree-json --json-only-output %s --top-module %s structural_primitives.sv %s 2>&1 > /dev/null"
        gen_json module_name generated_sv
    else
      Printf.sprintf "verilator --json-only --dump-tree-json --json-only-output %s --top-module %s %s 2>&1 > /dev/null"
        gen_json module_name generated_sv in
    let ret = Sys.command cmd in
    if ret <> 0 then begin
      Printf.fprintf stderr "  ✗ Verification FAILED: Could not parse generated Verilog\n";
      false
    end else begin
      (* Run Z3 verification *)
      Printf.fprintf stderr "  [Verify] Running Z3 equivalence check...\n";
      let orig_ast = translate_tree_to_ast original_json in
      let gen_ast = translate_tree_to_ast gen_json in

      match Sv_verify_hardcaml.check_equivalence orig_ast gen_ast with
      | true ->
          Printf.fprintf stderr "  ✓ Verification PASSED: Functionally equivalent\n";
          true
      | false ->
          Printf.fprintf stderr "  ✗ Verification FAILED: Not equivalent\n";
          false
    end
  with e ->
    Printf.fprintf stderr "  ✗ Verification EXCEPTION: %s\n" (Printexc.to_string e);
    false

(* Scan directory and process all files *)
let scan output_dir backend verify =
  let obj = "obj_dir/" in
  (try Unix.mkdir output_dir 0o750 with e -> Printf.eprintf "%s: %s\n" output_dir (Printexc.to_string e));
  let lst = ref [] in
  let fd = Unix.opendir obj in
  (try while true do
       let f = Unix.readdir(fd) in
       (* Only process main tree.json files, not intermediate passes like *_NNN_*.tree.json *)
       (* Intermediate files have _NNN_ patterns where NNN is exactly 3 digits *)
       (* Also skip verification output files that end with _verify.tree.json *)
       let is_intermediate =
         try
           let rex = Str.regexp "_[0-9][0-9][0-9]_" in
           Str.string_match rex f 0 || Str.search_forward rex f 0 >= 0
         with Not_found -> false in
       let is_verify_output = Filename.check_suffix f "_verify.tree.json" in
       if f.[0]<>'.' && Filename.check_suffix f ".tree.json" && not is_intermediate && not is_verify_output then
         lst := f :: !lst;
       done with End_of_file -> Unix.closedir fd);

  (* Track statistics *)
  let total_files = List.length !lst in
  let successful = ref 0 in
  let failed = ref 0 in
  let verified = ref 0 in
  let verify_failed = ref 0 in

  (* Open warnings file *)
  let warnings_file = output_dir ^ "warnings.txt" in
  let warnings_fd = open_out warnings_file in

  Printf.printf "Processing %d files with backend: %s%s\n\n" total_files
    (match backend with
     | Standard -> "Standard"
     | Structural -> "Structural"
     | Yosys -> "Yosys"
     | HardCaml -> "HardCaml")
    (if verify then " (with verification)" else "");

  List.iter (fun itm ->
    Printf.fprintf stderr "Processing %s...\n" itm;
    try
      let ast = translate_tree_to_ast (obj^itm) in
      Hashtbl.add asthash itm ast;

      (* Generate with selected backend *)
      let (result, warnings) = generate_output backend ast in

      (* Write output *)
      let ext = get_extension backend in
      let out_file = output_dir ^ "decompile_" ^ itm ^ ext in
      let fd = open_out out_file in
      output_string fd result;
      close_out fd;

      (* Write warnings for this file *)
      if List.length warnings > 0 then begin
        Printf.fprintf warnings_fd "\n=== %s ===\n" itm;
        List.iter (fun w -> Printf.fprintf warnings_fd "  WARNING: %s\n" w) warnings;
        Printf.fprintf stderr "  %d warnings generated\n" (List.length warnings)
      end else begin
        Printf.fprintf stderr "  Success\n"
      end;

      (* Run verification if requested *)
      if verify then begin
        if verify_output (obj^itm) out_file then
          incr verified
        else
          incr verify_failed
      end;

      incr successful
    with
    | Failure msg ->
        Printf.eprintf "  ✗ FAILED: %s\n" msg;
        incr failed
    | e ->
        Printf.eprintf "  ✗ EXCEPTION: %s\n" (Printexc.to_string e);
        incr failed
  ) !lst;

  close_out warnings_fd;

  (* Print summary *)
  Printf.printf "\n========================================\n";
  Printf.printf "Conversion Summary\n";
  Printf.printf "========================================\n";
  Printf.printf "Total files:  %d\n" total_files;
  Printf.printf "Successful:   %d\n" !successful;
  Printf.printf "Failed:       %d\n" !failed;
  if verify then begin
    Printf.printf "Verified:     %d\n" !verified;
    Printf.printf "Verify failed:%d\n" !verify_failed;
  end;
  Printf.printf "========================================\n";
  if !successful > 0 then
    Printf.printf "\nWarnings written to: %s\n" warnings_file

(* Process single file *)
let process_single_file json_file output_file backend =
  Printf.fprintf stderr "Processing %s with backend: %s\n" json_file
    (match backend with 
     | Standard -> "Standard" 
     | Structural -> "Structural" 
     | Yosys -> "Yosys"
     | HardCaml -> "HardCaml");
  let ast = translate_tree_to_ast json_file in
  let (result, warnings) = generate_output backend ast in
  
  (* Write output *)
  let fd = open_out output_file in
  output_string fd result;
  close_out fd;
  
  (* Print warnings *)
  if List.length warnings > 0 then begin
    Printf.fprintf stderr "\n=== WARNINGS ===\n";
    List.iter (fun w -> Printf.fprintf stderr "  WARNING: %s\n" w) warnings;
    Printf.fprintf stderr "\nTotal: %d warnings\n" (List.length warnings)
  end else begin
    Printf.fprintf stderr "Success - no warnings\n"
  end;
  Printf.fprintf stderr "Output written to: %s\n" output_file

(* Parse backend from string *)
let parse_backend s =
  match String.lowercase_ascii s with
  | "standard" | "std" -> Standard
  | "structural" | "struct" -> Structural
  | "yosys" -> Yosys
  | "hardcaml" | "hc" -> HardCaml
  | _ -> failwith ("Unknown backend: " ^ s)

(* Print usage *)
let print_usage () =
  Printf.eprintf "SystemVerilog Decompiler - Unified Backend Selector\n\n";
  Printf.eprintf "Usage:\n";
  Printf.eprintf "  %s scan <backend> <output_dir> [--verify]\n" Sys.argv.(0);
  Printf.eprintf "      Process all files in obj_dir/\n";
  Printf.eprintf "      --verify: Run Z3 verification (all backends)\n\n";
  Printf.eprintf "  %s file <backend> <json_file> <output_file>\n" Sys.argv.(0);
  Printf.eprintf "      Process single file\n\n";
  Printf.eprintf "Backends:\n";
  Printf.eprintf "  standard, std      - Original SystemVerilog output\n";
  Printf.eprintf "  structural, struct - Structural with primitives\n";
  Printf.eprintf "  yosys              - Yosys-compatible output\n";
  Printf.eprintf "  hardcaml, hc       - HardCaml OCaml output\n\n";
  Printf.eprintf "Examples:\n";
  Printf.eprintf "  %s scan yosys results/\n" Sys.argv.(0);
  Printf.eprintf "  %s scan hardcaml results/ --verify\n" Sys.argv.(0);
  Printf.eprintf "  %s file hardcaml input.json output.ml\n" Sys.argv.(0);
  exit 1

(* Main entry point *)
let () =
  if Array.length Sys.argv < 2 then
    print_usage ()
  else begin
    let mode = Sys.argv.(1) in
    try
      match mode with
      | "scan" when Array.length Sys.argv >= 4 ->
          let backend = parse_backend Sys.argv.(2) in
          let output_dir = Sys.argv.(3) in
          let output_dir = if output_dir.[String.length output_dir - 1] = '/'
                          then output_dir else output_dir ^ "/" in
          (* Check for --verify flag *)
          let verify = Array.length Sys.argv >= 5 && Sys.argv.(4) = "--verify" in
          scan output_dir backend verify
      | "file" when Array.length Sys.argv >= 5 ->
          let backend = parse_backend Sys.argv.(2) in
          let json_file = Sys.argv.(3) in
          let output_file = Sys.argv.(4) in
          process_single_file json_file output_file backend
      | _ -> print_usage ()
    with
    | Failure msg ->
        Printf.eprintf "Error: %s\n" msg;
        exit 1
    | e ->
        Printf.eprintf "Error: %s\n" (Printexc.to_string e);
        exit 1
  end
