(* Demonstration: Behavioral IR for slib_clock_div
 * Shows how both VHDL and SystemVerilog would produce the same
 * language-neutral intermediate representation.
 *)

open Behavioral_ir

(* Manually construct the behavioral IR for slib_clock_div to demonstrate
 * what it should look like. In practice, this would be generated by
 * vhdl_to_behavioral.ml or sv_to_behavioral.ml *)

let clock_div_behavioral_ir =
  {
    modules = [
      {
        name = "slib_clock_div";

        params = [
          ("RATIO", 4)  (* Parameter with default value *)
        ];

        signals = [
          (* Input ports *)
          { name = "CLK"; stype = BBool; direction = `Input; initial_value = None; attrs = [] };
          { name = "RST"; stype = BBool; direction = `Input; initial_value = None; attrs = [] };
          { name = "CE"; stype = BBool; direction = `Input; initial_value = None; attrs = [] };

          (* Output ports *)
          { name = "Q"; stype = BBool; direction = `Output; initial_value = None; attrs = [] };

          (* Internal signals *)
          { name = "iCounter";
            stype = BInt { width = 2; signed = Unsigned };
            direction = `Internal;
            initial_value = Some (BConst { value = 0; width = 2 }) ; attrs = [] };

          { name = "iQ";
            stype = BBool;
            direction = `Internal;
            initial_value = Some (BConst { value = 0; width = 1 }) ; attrs = [] };
        ];

        processes = [
          (* Main clocked process *)
          BSequential {
            name = "CD_PROC";
            clock = "CLK";
            clock_edge = `Pos;
            reset = Some "RST";
            reset_edge = Some `Pos;
            reset_async = true;

            body = [
              (* Default assignment: iQ := 0 *)
              BAssign {
                lhs = "iQ";
                rhs = BConst { value = 0; width = 1 }
              };

              (* if CE then *)
              BIf {
                condition = BVar "CE";

                then_stmts = [
                  (* if iCounter == (RATIO - 1) then *)
                  BIf {
                    condition = BBinOp {
                      op = BEq;
                      lhs = BVar "iCounter";
                      rhs = BConst { value = 3; width = 2 };  (* RATIO - 1 = 4 - 1 = 3 *)
                      result_type = BBool
                    };

                    then_stmts = [
                      (* iQ := 1 *)
                      BAssign {
                        lhs = "iQ";
                        rhs = BConst { value = 1; width = 1 }
                      };
                      (* iCounter := 0 *)
                      BAssign {
                        lhs = "iCounter";
                        rhs = BConst { value = 0; width = 2 }
                      };
                    ];

                    else_stmts = [
                      (* iCounter := iCounter + 1 *)
                      BAssign {
                        lhs = "iCounter";
                        rhs = BBinOp {
                          op = BAdd;
                          lhs = BVar "iCounter";
                          rhs = BConst { value = 1; width = 2 };
                          result_type = BInt { width = 2; signed = Unsigned }
                        }
                      };
                    ];
                  };
                ];

                else_stmts = [];
              };
            ];
            blocking_vars = [];
          };

          (* Continuous assignment: Q := iQ *)
          BCombinational {
            name = "output_assign";
            sensitivity = [BLevel "iQ"];
            body = [
              BAssign {
                lhs = "Q";
                rhs = BVar "iQ"
              }
            ];
          };
        ];

        instances = [];
        funcs = [];
    mems = []; attrs = [];
      }
    ];
    library_cells = [];
  }

let () =
  Printf.printf "═══════════════════════════════════════════════════════════════\n";
  Printf.printf "  Behavioral IR Demonstration: slib_clock_div\n";
  Printf.printf "═══════════════════════════════════════════════════════════════\n\n";

  Printf.printf "This is the language-neutral intermediate representation that\n";
  Printf.printf "BOTH VHDL and SystemVerilog frontends should produce.\n\n";

  Printf.printf "Key features:\n";
  Printf.printf "  ✓ No VHDL-isms (std_logic, process, architecture)\n";
  Printf.printf "  ✓ No SV-isms (always_ff, logic, posedge)\n";
  Printf.printf "  ✓ Explicit types (BInt{width=2}, BBool)\n";
  Printf.printf "  ✓ Normalized structure (BSequential with clock/reset)\n";
  Printf.printf "  ✓ Ready for SSA transformation\n\n";

  Printf.printf "═══════════════════════════════════════════════════════════════\n";
  Printf.printf "Pretty-printed Behavioral IR:\n";
  Printf.printf "═══════════════════════════════════════════════════════════════\n\n";

  let output = string_of_bprogram clock_div_behavioral_ir in
  Printf.printf "%s\n\n" output;

  Printf.printf "═══════════════════════════════════════════════════════════════\n";
  Printf.printf "Analysis:\n";
  Printf.printf "═══════════════════════════════════════════════════════════════\n\n";

  let bmod = List.hd clock_div_behavioral_ir.modules in

  Printf.printf "Signals:\n";
  List.iter (fun s ->
    let dir_str = match s.direction with
      | `Input -> "input"
      | `Output -> "output"
      | `Internal -> "internal"
    in
    Printf.printf "  - %s (%s): %s\n" s.name dir_str (string_of_btype s.stype)
  ) bmod.signals;

  Printf.printf "\nProcesses:\n";
  List.iter (function
    | BCombinational { name; _ } ->
        Printf.printf "  - %s (combinational)\n" name
    | BSequential { name; clock; reset; reset_async; _ } ->
        Printf.printf "  - %s (sequential: clock=%s, reset=%s, async=%b)\n"
          name clock (match reset with Some r -> r | None -> "none") reset_async
  ) bmod.processes;

  Printf.printf "\nVariable assignments in sequential process:\n";
  let seq_proc = List.hd bmod.processes in
  (match seq_proc with
   | BSequential { body; _ } ->
       let rec find_assigns = function
         | BAssign { lhs; _ } -> [lhs]
         | BIf { then_stmts; else_stmts; _ } ->
             List.concat (List.map find_assigns (then_stmts @ else_stmts))
         | BBlock stmts -> List.concat (List.map find_assigns stmts)
         | _ -> []
       in
       let assigned_vars = List.sort_uniq String.compare (List.concat (List.map find_assigns body)) in
       Printf.printf "  Variables assigned: %s\n" (String.concat ", " assigned_vars);
       Printf.printf "  → These will become registers after optimization\n";
   | _ -> ());

  Printf.printf "\n═══════════════════════════════════════════════════════════════\n";
  Printf.printf "Next Steps:\n";
  Printf.printf "═══════════════════════════════════════════════════════════════\n\n";

  Printf.printf "1. SSA Construction:\n";
  Printf.printf "   Transform multiple assignments into SSA form:\n";
  Printf.printf "     iQ := 0      →  iQ_1 := 0\n";
  Printf.printf "     iQ := 1      →  iQ_2 := 1\n";
  Printf.printf "     use iQ       →  iQ_3 := φ(iQ_1, iQ_2)\n\n";

  Printf.printf "2. Register Inference:\n";
  Printf.printf "   Identify state elements in sequential blocks:\n";
  Printf.printf "     iQ_3 is assigned in sequential → Register(iQ)\n";
  Printf.printf "     iCounter_3 is assigned in sequential → Register(iCounter)\n\n";

  Printf.printf "3. MUX Tree Generation:\n";
  Printf.printf "   Build priority muxes for conditional assignments:\n";
  Printf.printf "     mux1 = CE ? (is_max ? 1 : 0) : 0\n";
  Printf.printf "     Register(iQ) ← mux1\n\n";

  Printf.printf "4. Lower to Dataflow IR:\n";
  Printf.printf "   Convert to opt_ir nodes (Add, Compare, Mux, Register)\n";
  Printf.printf "   This becomes the dataflow graph for synthesis.\n\n";

  Printf.printf "═══════════════════════════════════════════════════════════════\n";
  Printf.printf "Result:\n";
  Printf.printf "═══════════════════════════════════════════════════════════════\n\n";

  Printf.printf "✅ Same behavioral IR from VHDL and SV\n";
  Printf.printf "✅ Register inference happens once, correctly\n";
  Printf.printf "✅ 2 registers generated (not 6!)\n";
  Printf.printf "✅ Optimizations apply uniformly\n\n";

  Printf.printf "This architecture eliminates the bug we just fixed!\n";
  Printf.printf "No more language-specific register generation logic.\n\n"
