// Generated by structural converter
// Primitives defined in: structural_primitives.sv

module fourstate (
  input logic clk,
  input logic reset,
  output logic [31:0] data
);
  logic [31:0] wire_3;
  logic [31:0] wire_1;
  logic [31:0] reg1;

  dff_en #(.WIDTH(32), .RESET_VAL(0)) dff_5 (
    .clk(clk),
    .rst(1'b0),
    .en(1'b1),
    .d(wire_3),
    .q(reg1)
  );
  mux2 #(.WIDTH(32)) mux_4 (
    .sel(reset),
    .in0(wire_1),
    .in1(32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx),
    .out(wire_3)
  );
  adder #(.WIDTH(32)) op_2 (
    .a(32'sh1),
    .b(reg1),
    .out(wire_1)
  );
  assign data = reg1;
endmodule