// Generated by structural converter
// Primitives defined in: structural_primitives.sv

module combinational (
  input logic [7:0] a,
  input logic [7:0] b,
  input logic sel,
  output logic [7:0] result
);
  logic [7:0] wire_1;

  mux2 #(.WIDTH(8)) mux_2 (
    .sel(sel),
    .in0(b),
    .in1(a),
    .out(wire_1)
  );
  assign result = wire_1;
endmodule