// Generated by structural converter
// Primitives defined in: structural_primitives.sv

module counter (
  input logic clk,
  input logic reset,
  output logic [7:0] count
);
  logic [7:0] wire_3;
  logic [7:0] wire_1;
  logic [7:0] count_reg;

  dff_en #(.WIDTH(8), .RESET_VAL(0)) dff_5 (
    .clk(clk),
    .rst(1'b0),
    .en(1'b1),
    .d(wire_3),
    .q(count_reg)
  );
  mux2 #(.WIDTH(8)) mux_4 (
    .sel(reset),
    .in0(wire_1),
    .in1(8'h0),
    .out(wire_3)
  );
  adder #(.WIDTH(8)) op_2 (
    .a(8'h1),
    .b(count_reg),
    .out(wire_1)
  );
  assign count = count_reg;
endmodule