// Generated by structural converter
// Primitives defined in: structural_primitives.sv

module large_memory (
  input logic clk,
  input logic [4:0] addr,
  input logic [31:0] wdata,
  input logic we,
  output logic [31:0] rdata
);
  logic [31:0] mem_rdata;

  memory_sp #(.ADDR_WIDTH(5), .DATA_WIDTH(32)) mem_inst (
    .clk(clk),
    .we(we),
    .addr(addr),
    .wdata(wdata),
    .rdata(mem_rdata)
  );
  dff_en #(.WIDTH(32), .RESET_VAL(0)) dff_2 (
    .clk(clk),
    .rst(1'b0),
    .en(1'b1),
    .d(mem_rdata),
    .q(rdata)
  );
  dff_en #(.WIDTH(32), .RESET_VAL(0)) dff_1 (
    .clk(clk),
    .rst(1'b0),
    .en(we),
    .d(wdata),
    .q(mem_rdata)
  );
endmodule