// Generated by structural converter
// Primitives defined in: structural_primitives.sv

module mixed (
  input logic clk,
  input logic [7:0] a,
  input logic [7:0] b,
  output logic [7:0] sum,
  output logic [7:0] sum_reg
);
  logic [7:0] wire_4;
  logic [7:0] wire_1;

  adder #(.WIDTH(8)) op_5 (
    .a(a),
    .b(b),
    .out(wire_4)
  );
  dff_en #(.WIDTH(8), .RESET_VAL(0)) dff_3 (
    .clk(clk),
    .rst(1'b0),
    .en(1'b1),
    .d(wire_1),
    .q(sum_reg)
  );
  adder #(.WIDTH(8)) op_2 (
    .a(a),
    .b(b),
    .out(wire_1)
  );
  assign sum = wire_4;
endmodule