// Generated by structural converter
// Primitives defined in: structural_primitives.sv

module pipeline (
  input logic clk,
  input logic [31:0] data_in,
  output logic [31:0] data_out
);
  logic [31:0] stage1;
  logic [31:0] stage2;
  logic [31:0] stage3;

  dff_en #(.WIDTH(32), .RESET_VAL(0)) dff_3 (
    .clk(clk),
    .rst(1'b0),
    .en(1'b1),
    .d(stage2),
    .q(stage3)
  );
  dff_en #(.WIDTH(32), .RESET_VAL(0)) dff_2 (
    .clk(clk),
    .rst(1'b0),
    .en(1'b1),
    .d(stage1),
    .q(stage2)
  );
  dff_en #(.WIDTH(32), .RESET_VAL(0)) dff_1 (
    .clk(clk),
    .rst(1'b0),
    .en(1'b1),
    .d(data_in),
    .q(stage1)
  );
  assign data_out = stage3;
endmodule