// Generated by structural converter
// Primitives defined in: structural_primitives.sv

module small_memory (
  input logic clk,
  input logic [1:0] addr,
  input logic [7:0] wdata,
  input logic we,
  output logic [7:0] rdata
);
  logic [7:0] [0:3] mem;

  dff_en #(.WIDTH(8), .RESET_VAL(0)) dff_2 (
    .clk(clk),
    .rst(1'b0),
    .en(1'b1),
    .d(mem[addr]),
    .q(rdata)
  );
  dff_en #(.WIDTH(8), .RESET_VAL(0)) dff_1 (
    .clk(clk),
    .rst(1'b0),
    .en(we),
    .d(wdata),
    .q(mem[addr])
  );
endmodule