(* OpenROAD ECO change-list emitter (#94).

   Given a predict_swap recommendation, emit a self-contained
   pair of scripts the user runs to apply the swap:

   1.  <out_dir>/eco.ys
       A Yosys script that re-synthesises the swapped binding's
       RTL with the new sv_decomp_{adder,mul} attribute.  The
       output Verilog is written to <out_dir>/eco_swap.v.

   2.  <out_dir>/eco.tcl
       An OpenROAD Tcl script that:
         - reads the original DEF + Liberty
         - reads the new gate-level Verilog
         - swaps the old binding's instances for the new ones
         - re-places affected cells (incremental)
         - re-routes the ECO region
         - re-runs report_checks to confirm the speed-up

   3.  <out_dir>/eco_swaps.txt
       Human-readable change list: which instances are removed,
       which are added, expected savings.

   This is a recipe, not an executable change — the user runs
   eco.ys + eco.tcl in their flow.  For our purposes the
   emitter is verified by inspecting the scripts and by the
   downstream #96 equivalence check on the post-swap netlist. *)

let ensure_dir path =
  if not (Sys.file_exists path) then Unix.mkdir path 0o755
  else if not (Sys.is_directory path) then
    failwith (path ^ " exists but is not a directory")

let emit_yosys_script ~oc ~rtl_path ~top ~binding ~kind ~to_arch ~out_v =
  let p fmt = Printf.fprintf oc fmt in
  p "# Auto-generated by Lef_def.Eco_emit\n";
  p "# Re-synthesise %s/%s with sv_decomp_%s = \"%s\"\n\n"
    top binding kind to_arch;
  p "read_verilog -sv %s\n" rtl_path;
  p "hierarchy -top %s\n" top;
  (* Yosys lacks a built-in for arch attributes; the convention
     in our flow is to set an environment variable picked up by
     the SV preprocessor.  See verify-arch for the same hook. *)
  p "# arch knob comes from SV (* sv_decomp_%s = \"%s\" *)\n"
    kind to_arch;
  p "# applied to wire/instance %s in the source.\n\n" binding;
  p "synth -flatten\n";
  p "abc -liberty $::env(LIBERTY_FILE)\n";
  p "techmap\n";
  p "write_verilog %s\n" out_v

let emit_openroad_tcl
    ~oc ~def_path ~lib_path ~lef_path ~new_v_path
    ~binding_inst_prefix ~bbox =
  let p fmt = Printf.fprintf oc fmt in
  p "# Auto-generated by Lef_def.Eco_emit\n";
  p "# OpenROAD ECO Tcl: incremental swap of %s region\n\n"
    binding_inst_prefix;

  p "# 1. Read inputs\n";
  p "read_lef     %s\n" lef_path;
  p "read_liberty %s\n" lib_path;
  p "read_def     %s\n\n" def_path;

  p "# 2. Read the freshly-synthesised replacement netlist\n";
  p "read_verilog %s\n" new_v_path;
  p "link_design  mac\n\n";

  p "# 3. Identify the cells to remove (the current binding's members)\n";
  p "set old_insts [get_cells -filter \"name =~ %s*\"]\n"
    binding_inst_prefix;
  p "puts \"ECO: %%d cells in current binding\" [llength $old_insts]\n\n";

  p "# 4. Replace one-for-one.  This is the fragile step — relies on\n";
  p "#    the new netlist exposing the same external ports as the old\n";
  p "#    binding.  Cert-gated swap (#95) guarantees that.\n";
  p "foreach inst $old_insts {\n";
  p "  set master_old [get_cell_master $inst]\n";
  p "  set master_new [get_swap_target $inst]   ;# user-defined\n";
  p "  if {$master_new ne {}} {\n";
  p "    replace_cell $inst $master_new\n";
  p "  }\n";
  p "}\n\n";

  let pad = 2000 in
  let xa, ya, xb, yb =
    match bbox with
    | None -> (0, 0, 100000, 100000)
    | Some ((xa,ya),(xb,yb)) -> (xa - pad, ya - pad, xb + pad, yb + pad) in
  p "# 5. Re-place + re-route the ECO bbox (padded by %d dbu)\n" pad;
  p "set eco_bbox {%d %d %d %d}\n" xa ya xb yb;
  p "place_design -incremental -region $eco_bbox\n";
  p "detail_route -region $eco_bbox\n\n";

  p "# 6. Verify timing improved\n";
  p "report_checks -path_delay max -fields {slew cap} -path_count 1\n";
  p "report_design_area\n"

let emit_swap_log ~oc ~pred =
  let p fmt = Printf.fprintf oc fmt in
  let c = pred.Predict_swap.cand in
  p "ECO swap recommendation\n";
  p "=======================\n\n";
  p "Binding         : %s\n"   c.binding_name;
  p "Current arch    : %s\n"   c.current_arch;
  p "Target arch     : %s\n"   c.to_arch;
  p "Kind / width    : %s @ %d\n" c.kind c.width;
  p "Cert status     : %s\n"
    (Predict_swap.string_of_cert pred.cert);
  p "\n";
  p "Critical-path metrics\n";
  p "  cells in cone : %d\n"     pred.cells_in_cone;
  p "  cone delay    : %.1f ps\n" pred.cone_delay_ps;
  p "  predicted save: %.1f ps\n" pred.predicted_savings;
  p "  new arrival   : %.1f ps\n" pred.predicted_new_arr;
  p "\n";
  p "Apply with:\n";
  p "  yosys -s   eco.ys     # re-synthesise new arch\n";
  p "  openroad -s eco.tcl   # incremental ECO\n"

(* The top-level emitter takes the inputs the user already has\n
   in hand and writes the three artefacts. *)

type artefacts = {
  yosys_path     : string;
  openroad_path  : string;
  log_path       : string;
  new_v_path     : string;     (* path the Yosys script will write *)
}

let emit
    ~out_dir ~rtl_path ~top
    ~def_path ~lib_path ~lef_path
    ~bbox ~prediction =
  ensure_dir out_dir;
  let yp  = Filename.concat out_dir "eco.ys" in
  let tcl = Filename.concat out_dir "eco.tcl" in
  let log = Filename.concat out_dir "eco_swaps.txt" in
  let new_v = Filename.concat out_dir "eco_swap.v" in

  let oc = open_out yp in
  emit_yosys_script ~oc ~rtl_path ~top
    ~binding:prediction.Predict_swap.cand.binding_name
    ~kind:prediction.cand.kind
    ~to_arch:prediction.cand.to_arch
    ~out_v:new_v;
  close_out oc;

  let oc = open_out tcl in
  emit_openroad_tcl ~oc ~def_path ~lib_path ~lef_path
    ~new_v_path:new_v
    ~binding_inst_prefix:prediction.cand.binding_name
    ~bbox;
  close_out oc;

  let oc = open_out log in
  emit_swap_log ~oc ~pred:prediction;
  close_out oc;

  { yosys_path = yp; openroad_path = tcl; log_path = log; new_v_path = new_v }
